extends Object
enum {
	ITEMS,
	MEDICINE,
	BALLS,
	TMS,
	BERRIES,
	BATTLE_ITEMS,
	KEY_ITEMS,
}

var item_list = { # Generated 1:1 from the official items.dat (name, description, pocket)
	1: Item.new("Repel", "An item that prevents weak wild Pokémon from appearing for 100 steps after its use.", ITEMS),
	2: Item.new("Super Repel", "An item that prevents weak wild Pokémon from appearing for 200 steps after its use.", ITEMS),
	3: Item.new("Max Repel", "An item that prevents weak wild Pokémon from appearing for 250 steps after its use.", ITEMS),
	4: Item.new("Black Flute", "A black flute made from blown glass. Its melody makes wild Pokémon less likely to appear.", ITEMS),
	5: Item.new("White Flute", "A white flute made from blown glass. Its melody makes wild Pokémon more likely to appear.", ITEMS),
	6: Item.new("Honey", "A sweet honey with an aroma that attracts wild Pokémon when used in grass, caves or on special trees.", ITEMS),
	7: Item.new("Escape Rope", "A long, durable rope. Use it to escape instantly from a cave or a dungeon.", ITEMS),
	8: Item.new("Red Shard", "A small red shard. It appears to be from some sort of implement made long ago.", ITEMS),
	9: Item.new("Blue Shard", "A small blue shard. It appears to be from some sort of implement made long ago.", ITEMS),
	10: Item.new("Yellow Shard", "A small yellow shard. It appears to be from some sort of implement made long ago.", ITEMS),
	11: Item.new("Green Shard", "A small green shard. It appears to be from some sort of implement made long ago.", ITEMS),
	12: Item.new("Fire Stone", "A peculiar stone that makes certain species of Pokémon evolve. It is colored orange.", ITEMS),
	13: Item.new("Water Stone", "A peculiar stone that makes certain species of Pokémon evolve. It is a clear, light blue.", ITEMS),
	14: Item.new("Thunderstone", "A peculiar stone that makes certain species of Pokémon evolve. It has a thunderbolt pattern.", ITEMS),
	15: Item.new("Leaf Stone", "A peculiar stone that makes certain species of Pokémon evolve. It has a leaf pattern.", ITEMS),
	16: Item.new("Moon Stone", "A peculiar stone that makes certain species of Pokémon evolve. It is as black as the night sky.", ITEMS),
	17: Item.new("Sun Stone", "A peculiar stone that makes certain species of Pokémon evolve. It is as red as the sun.", ITEMS),
	18: Item.new("Shiny Stone", "A peculiar stone that makes certain species of Pokémon evolve. It shines with a dazzling light.", ITEMS),
	19: Item.new("Dusk Stone", "A peculiar stone that makes certain species of Pokémon evolve. It is as dark as dark can be.", ITEMS),
	20: Item.new("Dawn Stone", "A peculiar stone that makes certain species of Pokémon evolve. It sparkles like eyes.", ITEMS),
	21: Item.new("Oval Stone", "A peculiar stone that makes certain species of Pokémon evolve. It is shaped like an egg.", ITEMS),
	22: Item.new("Helix Fossil", "A fossil of an ancient Pokémon that lived in the sea. It appears to be part of a seashell.", ITEMS),
	23: Item.new("Dome Fossil", "A fossil of an ancient Pokémon that lived in the sea. It appears to be part of a shell.", ITEMS),
	24: Item.new("Old Amber", "A piece of clear amber that contains the genetic material of an ancient Pokémon.", ITEMS),
	25: Item.new("Root Fossil", "A fossil of an ancient Pokémon that lived in the sea. It appears to be part of a plant root.", ITEMS),
	26: Item.new("Claw Fossil", "A fossil of an ancient Pokémon that lived in the sea. It appears to be part of a claw.", ITEMS),
	27: Item.new("Armor Fossil", "A fossil from a prehistoric Pokémon that lived on the land. It appears to be part of a collar.", ITEMS),
	28: Item.new("Skull Fossil", "A fossil from a prehistoric Pokémon that lived on the land. It appears to be part of a head.", ITEMS),
	29: Item.new("TinyMushroom", "A small and rare mushroom. It is quite popular among certain maniacal fan segments.", ITEMS),
	30: Item.new("Big Mushroom", "A large and rare mushroom. It is very popular among certain maniacal fan segments.", ITEMS),
	31: Item.new("Pearl", "A somewhat-small pearl that sparkles in a pretty silver color. It can be sold cheaply to shops.", ITEMS),
	32: Item.new("Big Pearl", "A quite-large pearl that sparkles in a pretty silver color. It can be sold at a high price to shops.", ITEMS),
	33: Item.new("Stardust", "Lovely, red-colored sand with a loose, silky feel. It can be sold at a high price to shops.", ITEMS),
	34: Item.new("Star Piece", "A shard of a pretty gem that sparkles in a red color. It can be sold at a high price to shops.", ITEMS),
	35: Item.new("Nugget", "A nugget of pure gold that gives off a lustrous gleam. It can be sold at a high price to shops.", ITEMS),
	36: Item.new("Heart Scale", "A pretty, heart-shaped scale that is extremely rare. It glows faintly in the colors of the rainbow.", ITEMS),
	37: Item.new("Rare Bone", "A bone that is extremely valuable for Pokémon archaeology. It can be sold for a high price to shops.", ITEMS),
	38: Item.new("Shoal Salt", "Pure salt that was discovered deep inside the Shoal Cave. It is extremely salty.", ITEMS),
	39: Item.new("Shoal Shell", "A pretty seashell that was found deep inside the Shoal Cave. It is striped in blue and white.", ITEMS),
	40: Item.new("Odd Keystone", "A vital item that is needed to keep a stone tower from collapsing. Voices can be heard from it occasionally.", ITEMS),
	41: Item.new("Growth Mulch", "A plant fertilizer. It speeds up the growth of Berries. However, it also dries the soil faster.", BERRIES),
	42: Item.new("Damp Mulch", "A plant fertilizer. It slows the growth of Berries and causes the soil to dry slower.", BERRIES),
	43: Item.new("Stable Mulch", "A plant fertilizer. It extends the time ripened Berries remain on their plants before falling.", BERRIES),
	44: Item.new("Gooey Mulch", "A plant fertilizer. It ups the number of times new plants grow where mature plants withered.", BERRIES),
	45: Item.new("Red Apricorn", "A red Apricorn. It assails your nostrils.", ITEMS),
	46: Item.new("Ylw Apricorn", "A yellow Apricorn. It has an invigorating scent.", ITEMS),
	47: Item.new("Blu Apricorn", "A blue Apricorn. It smells a bit like grass.", ITEMS),
	48: Item.new("Grn Apricorn", "A green Apricorn. It has a mysterious, aromatic scent.", ITEMS),
	49: Item.new("Pnk Apricorn", "A pink Apricorn. It has a nice, sweet scent.", ITEMS),
	50: Item.new("Wht Apricorn", "A white Apricorn. It doesn't smell like anything.", ITEMS),
	51: Item.new("Blk Apricorn", "A black Apricorn. It has an indescribable scent.", ITEMS),
	52: Item.new("BrightPowder", "An item to be held by a Pokémon. It casts a tricky glare that lowers the opponent's accuracy.", ITEMS),
	53: Item.new("White Herb", "An item to be held by a Pokémon. It restores any lowered stat in battle. It can be used only once.", ITEMS),
	54: Item.new("Exp. Share", "An item to be held by a Pokémon. The holder gets a share of a battle's Exp. Points without battling.", ITEMS),
	55: Item.new("Quick Claw", "An item to be held by a Pokémon. A light, sharp claw that lets the bearer move first occasionally.", ITEMS),
	56: Item.new("Soothe Bell", "An item to be held by a Pokémon. It is a bell with a comforting chime that calms the holder.", ITEMS),
	57: Item.new("Mental Herb", "An item to be held by a Pokémon. It snaps the holder out of infatuation, just once.", ITEMS),
	58: Item.new("King's Rock", "An item to be held by a Pokémon. It may cause the foe to flinch when the holder inflicts damage.", ITEMS),
	59: Item.new("SilverPowder", "An item to be held by a Pokémon. It is a shiny, silver powder that ups the power of Bug-type moves.", ITEMS),
	60: Item.new("Amulet Coin", "An item to be held by a Pokémon. It doubles a battle's prize money if the holding Pokémon joins in.", ITEMS),
	61: Item.new("Cleanse Tag", "An item to be held by a Pokémon. It helps keep wild Pokémon away if the holder is the first one in the party.", ITEMS),
	62: Item.new("Smoke Ball", "An item to be held by a Pokémon. It enables the holder to flee from any wild Pokémon without fail.", ITEMS),
	63: Item.new("Everstone", "An item to be held by a Pokémon. The Pokémon holding this peculiar stone is prevented from evolving.", ITEMS),
	64: Item.new("Focus Band", "An item to be held by a Pokémon. The holder may endure a potential KO attack, leaving it with just 1 HP.", ITEMS),
	65: Item.new("Lucky Egg", "An item to be held by a Pokémon. It is an egg filled with happiness that earns extra Exp. Points in battle.", ITEMS),
	66: Item.new("Scope Lens", "An item to be held by a Pokémon. It is a lens that boosts the holder's critical-hit ratio.", ITEMS),
	67: Item.new("Wide Lens", "An item to be held by a Pokémon. It is a magnifying lens that slightly boosts the accuracy of moves.", ITEMS),
	68: Item.new("Zoom Lens", "An item to be held by a Pokémon. If the holder moves after the foe, its critical-hit ratio will be boosted.", ITEMS),
	69: Item.new("Metal Coat", "An item to be held by a Pokémon. It is a special metallic film that ups the power of Steel-type moves.", ITEMS),
	70: Item.new("Leftovers", "An item to be held by a Pokémon. The holder's HP is gradually restored during battle.", ITEMS),
	71: Item.new("Dragon Scale", "A thick and tough scale. Dragon-type Pokémon may be holding this item when caught.", ITEMS),
	72: Item.new("Shell Bell", "An item to be held by a Pokémon. The holder's HP is restored a little every time it inflicts damage.", ITEMS),
	73: Item.new("Muscle Band", "An item to be held by a Pokémon. It is a headband that slightly boosts the power of physical moves.", ITEMS),
	74: Item.new("Wise Glasses", "An item to be held by a Pokémon. It is a thick pair of glasses that boosts the power of special moves.", ITEMS),
	75: Item.new("Expert Belt", "An item to be held by a Pokémon. It is a well-worn belt that boosts the power of supereffective moves.", ITEMS),
	76: Item.new("Life Orb", "An item to be held by a Pokémon. It boosts the power of moves, but at the cost of some HP on each hit.", ITEMS),
	77: Item.new("Power Herb", "A single-use item to be held by a Pokémon. It allows the immediate use of a move that charges.", ITEMS),
	78: Item.new("Toxic Orb", "An item to be held by a Pokémon. It is a bizarre orb that badly poisons the holder in battle.", ITEMS),
	79: Item.new("Flame Orb", "An item to be held by a Pokémon. It is a bizarre orb that inflicts a burn on the holder in battle.", ITEMS),
	80: Item.new("Focus Sash", "An item to be held by a Pokémon. If it has full HP, the holder will endure a potential KO attack.", ITEMS),
	81: Item.new("Metronome", "A Pokémon hold item that boosts a move used consecutively.", ITEMS),
	82: Item.new("Iron Ball", "A Pokémon hold item that cuts Speed. It makes airborne holders susceptible to Ground moves.", ITEMS),
	83: Item.new("Lagging Tail", "An item to be held by a Pokémon. It is tremendously heavy and makes the holder move slower than usual.", ITEMS),
	84: Item.new("Destiny Knot", "A long, bright red string to be held by a Pokémon. If the holder becomes infatuated, the foe does too.", ITEMS),
	85: Item.new("Black Sludge", "A hold item that gradually restores the HP of Poison-type Pokémon. It inflicts damage on all other types.", ITEMS),
	86: Item.new("Grip Claw", "A Pokémon hold item that extends the duration of multiturn attacks like Bind and Wrap.", ITEMS),
	87: Item.new("Sticky Barb", "A hold item that damages the holder on every turn. It may latch on to foes that touch the holder.", ITEMS),
	88: Item.new("Shed Shell", "A tough, discarded carapace to be held by a Pokémon. It enables the holder to switch out of battle.", ITEMS),
	89: Item.new("Big Root", "A Pokémon hold item that boosts the power of HP-stealing moves to let the holder recover more HP.", ITEMS),
	90: Item.new("Choice Band", "An item to be held by a Pokémon. This headband ups Attack, but allows the use of only one kind of move.", ITEMS),
	91: Item.new("Choice Specs", "A Pokémon hold item. These distinctive glasses boost Sp. Atk, but allow only one move to be used.", ITEMS),
	92: Item.new("Choice Scarf", "An item to be held by a Pokémon. This scarf boosts Speed, but allows the use of only one kind of move.", ITEMS),
	93: Item.new("Light Clay", "A Pokémon hold item that extends the duration of barrier moves like Light Screen and Reflect.", ITEMS),
	94: Item.new("Icy Rock", "A Pokémon hold item that extends the duration of the move Hail used by the holder.", ITEMS),
	95: Item.new("Smooth Rock", "A Pokémon hold item that extends the duration of the move Sandstorm used by the holder.", ITEMS),
	96: Item.new("Heat Rock", "A Pokémon hold item that extends the duration of the move Sunny Day used by the holder.", ITEMS),
	97: Item.new("Damp Rock", "A Pokémon hold item that extends the duration of the move Rain Dance used by the holder.", ITEMS),
	98: Item.new("Macho Brace", "A Pokémon hold item that is a stiff and heavy brace that promotes strong growth but lowers Speed.", ITEMS),
	99: Item.new("Power Bracer", "A Pokémon hold item that promotes Attack gain on leveling, but reduces the Speed stat.", ITEMS),
	100: Item.new("Power Belt", "A Pokémon hold item that promotes Defense gain on leveling, but reduces the Speed stat.", ITEMS),
	101: Item.new("Power Lens", "A Pokémon hold item that promotes Sp. Atk gain on leveling, but reduces the Speed stat.", ITEMS),
	102: Item.new("Power Band", "A Pokémon hold item that promotes Sp. Def gain on leveling, but reduces the Speed stat.", ITEMS),
	103: Item.new("Power Anklet", "A Pokémon hold item that promotes Speed gain on leveling, but reduces the Speed stat.", ITEMS),
	104: Item.new("Power Weight", "A Pokémon hold item that promotes HP gain on leveling, but reduces the Speed stat.", ITEMS),
	105: Item.new("Sea Incense", "A Pokémon hold item. It is incense with a curious aroma that boosts the power of Water-type moves.", ITEMS),
	106: Item.new("Lax Incense", "A Pokémon hold item. The tricky aroma of this incense lowers the foe's accuracy.", ITEMS),
	107: Item.new("Odd Incense", "A Pokémon hold item. It is an exotic-smelling incense that boosts the power of Psychic-type moves.", ITEMS),
	108: Item.new("Rock Incense", "A Pokémon hold item. It is an exotic-smelling incense that boosts the power of Rock-type moves.", ITEMS),
	109: Item.new("Full Incense", "A Pokémon hold item. It is an exotic-smelling incense that makes the holder bloated and slow moving.", ITEMS),
	110: Item.new("Wave Incense", "A Pokémon hold item. It is an exotic-smelling incense that boosts the power of Water-type moves.", ITEMS),
	111: Item.new("Rose Incense", "A Pokémon hold item. It is an exotic-smelling incense that boosts the power of Grass-type moves.", ITEMS),
	112: Item.new("Luck Incense", "An item to be held by a Pokémon. It doubles a battle's prize money if the holding Pokémon joins in.", ITEMS),
	113: Item.new("Pure Incense", "An item to be held by a Pokémon. It helps keep wild Pokémon away if the holder is the first one in the party.", ITEMS),
	114: Item.new("Soft Sand", "An item to be held by a Pokémon. It is a loose, silky sand that boosts the power of Ground-type moves.", ITEMS),
	115: Item.new("Hard Stone", "An item to be held by a Pokémon. It is an unbreakable stone that ups the power of Rock-type moves.", ITEMS),
	116: Item.new("Miracle Seed", "An item to be held by a Pokémon. It is a seed imbued with life that ups the power of Grass-type moves.", ITEMS),
	117: Item.new("BlackGlasses", "An item to be held by a Pokémon. It is a shady-looking pair of glasses that boosts Dark-type moves.", ITEMS),
	118: Item.new("Black Belt", "An item to be held by a Pokémon. It is a belt that boosts determination and Fighting-type moves.", ITEMS),
	119: Item.new("Magnet", "An item to be held by a Pokémon. It is a powerful magnet that boosts the power of Electric-type moves.", ITEMS),
	120: Item.new("Mystic Water", "An item to be held by a Pokémon. It is a teardrop-shaped gem that ups the power of Water-type moves.", ITEMS),
	121: Item.new("Sharp Beak", "An item to be held by a Pokémon. It is a long, sharp beak that boosts the power of Flying-type moves.", ITEMS),
	122: Item.new("Poison Barb", "An item to be held by a Pokémon. It is a small, poisonous barb that ups the power of Poison-type moves.", ITEMS),
	123: Item.new("NeverMeltIce", "An item to be held by a Pokémon. It is a piece of ice that repels heat and boosts Ice-type moves.", ITEMS),
	124: Item.new("Spell Tag", "An item to be held by a Pokémon. It is a sinister, eerie tag that boosts the power of Ghost-type moves.", ITEMS),
	125: Item.new("TwistedSpoon", "A Pokémon hold item. It is a spoon imbued with telekinetic power that boosts Psychic-type moves.", ITEMS),
	126: Item.new("Charcoal", "An item to be held by a Pokémon. It is a combustible fuel that boosts the power of Fire-type moves.", ITEMS),
	127: Item.new("Dragon Fang", "An item to be held by a Pokémon. It is a hard and sharp fang that ups the power of Dragon-type moves.", ITEMS),
	128: Item.new("Silk Scarf", "An item to be held by a Pokémon. It is a sumptuous scarf that boosts the power of Normal-type moves.", ITEMS),
	129: Item.new("Flame Plate", "An item to be held by a Pokémon. It is a stone tablet that boosts the power of Fire-type moves.", ITEMS),
	130: Item.new("Splash Plate", "An item to be held by a Pokémon. It is a stone tablet that boosts the power of Water-type moves.", ITEMS),
	131: Item.new("Zap Plate", "An item to be held by a Pokémon. It is a stone tablet that boosts the power of Electric-type moves.", ITEMS),
	132: Item.new("Meadow Plate", "An item to be held by a Pokémon. It is a stone tablet that boosts the power of Grass-type moves.", ITEMS),
	133: Item.new("Icicle Plate", "An item to be held by a Pokémon. It is a stone tablet that boosts the power of Ice-type moves.", ITEMS),
	134: Item.new("Fist Plate", "An item to be held by a Pokémon. It is a stone tablet that boosts the power of Fighting-type moves.", ITEMS),
	135: Item.new("Toxic Plate", "An item to be held by a Pokémon. It is a stone tablet that boosts the power of Poison-type moves.", ITEMS),
	136: Item.new("Earth Plate", "An item to be held by a Pokémon. It is a stone tablet that boosts the power of Ground-type moves.", ITEMS),
	137: Item.new("Sky Plate", "An item to be held by a Pokémon. It is a stone tablet that boosts the power of Flying-type moves.", ITEMS),
	138: Item.new("Mind Plate", "An item to be held by a Pokémon. It is a stone tablet that boosts the power of Psychic-type moves.", ITEMS),
	139: Item.new("Insect Plate", "An item to be held by a Pokémon. It is a stone tablet that boosts the power of Bug-type moves.", ITEMS),
	140: Item.new("Stone Plate", "An item to be held by a Pokémon. It is a stone tablet that boosts the power of Rock-type moves.", ITEMS),
	141: Item.new("Spooky Plate", "An item to be held by a Pokémon. It is a stone tablet that boosts the power of Ghost-type moves.", ITEMS),
	142: Item.new("Draco Plate", "An item to be held by a Pokémon. It is a stone tablet that boosts the power of Dragon-type moves.", ITEMS),
	143: Item.new("Dread Plate", "An item to be held by a Pokémon. It is a stone tablet that boosts the power of Dark-type moves.", ITEMS),
	144: Item.new("Iron Plate", "An item to be held by a Pokémon. It is a stone tablet that boosts the power of Steel-type moves.", ITEMS),
	145: Item.new("Light Ball", "An item to be held by Pikachu. It is a puzzling orb that raises the Sp. Atk stat.", ITEMS),
	146: Item.new("Lucky Punch", "An item to be held by Chansey. It is a pair of gloves that boosts CHANSEY's critical-hit ratio.", ITEMS),
	147: Item.new("Metal Powder", "An item to be held by Ditto. Extremely fine yet hard, this odd powder boosts the Defense stat.", ITEMS),
	148: Item.new("Quick Powder", "An item to be held by Ditto. Extremely fine yet hard, this odd powder boosts the Speed stat.", ITEMS),
	149: Item.new("Thick Club", "An item to be held by Cubone or Marowak. It is a hard bone of some sort that boosts the Attack stat.", ITEMS),
	150: Item.new("Stick", "An item to be held by Farfetch'd. It is a long and stiff leek stalk that boosts the critical-hit ratio.", ITEMS),
	151: Item.new("Soul Dew", "A wondrous orb to be held by Latios or Latias. It raises both the Sp. Atk and Sp. Def stats.", ITEMS),
	152: Item.new("DeepSeaTooth", "An item to be held by Clamperl. A fang that gleams a sharp silver, it raises the Sp. Atk stat.", ITEMS),
	153: Item.new("DeepSeaScale", "An item to be held by Clamperl. A scale that shines a faint pink, it raises the Sp. Def stat.", ITEMS),
	154: Item.new("Adamant Orb", "A brightly gleaming orb to be held by Dialga. It boosts the power of Dragon- and Steel-type moves.", ITEMS),
	155: Item.new("Lustrous Orb", "A beautifully glowing orb to be held by Palkia. It boosts the power of Dragon- and Water-type moves.", ITEMS),
	156: Item.new("Griseous Orb", "A glowing orb to be held by Giratina. It boosts the power of Dragon- and Ghost-type moves.", ITEMS),
	157: Item.new("Up-Grade", "A transparent device filled with all sorts of data. It was produced by Silph Co.", ITEMS),
	158: Item.new("Dubious Disc", "A transparent device overflowing with dubious data. Its producer is unknown.", ITEMS),
	159: Item.new("Protector", "A protective item of some sort. It is extremely stiff and heavy. It is loved by a certain Pokémon.", ITEMS),
	160: Item.new("Electirizer", "A box packed with a tremendous amount of electric energy. It is loved by a certain Pokémon.", ITEMS),
	161: Item.new("Magmarizer", "A box packed with a tremendous amount of magma energy. It is loved by a certain Pokémon.", ITEMS),
	162: Item.new("Reaper Cloth", "A cloth imbued with horrifyingly strong spiritual energy. It is loved by a certain Pokémon.", ITEMS),
	163: Item.new("Razor Claw", "An item to be held by a Pokémon. It is a sharply hooked claw that ups the holder's critical-hit ratio.", ITEMS),
	164: Item.new("Razor Fang", "An item to be held by a Pokémon. It may cause the foe to flinch when the holder inflicts damage.", ITEMS),
	165: Item.new("Red Scarf", "An item to be held by a Pokémon. It boosts the “Cool” aspect of the holder in a Contest.", ITEMS),
	166: Item.new("Blue Scarf", "An item to be held by a Pokémon. It boosts the “Beauty” aspect of the holder in a Contest.", ITEMS),
	167: Item.new("Pink Scarf", "An item to be held by a Pokémon. It boosts the “Cute” aspect of the holder in a Contest.", ITEMS),
	168: Item.new("Green Scarf", "An item to be held by a Pokémon. It boosts the “Smart” aspect of the holder in a Contest.", ITEMS),
	169: Item.new("Yellow Scarf", "An item to be held by a Pokémon. It boosts the “Tough” aspect of the holder in a Contest.", ITEMS),
	170: Item.new("Potion", "A spray-type medicine for wounds. It restores the HP of one Pokémon by just 20 points.", MEDICINE),
	171: Item.new("Super Potion", "A spray-type medicine for wounds. It restores the HP of one Pokémon by 50 points.", MEDICINE),
	172: Item.new("Hyper Potion", "A spray-type medicine for wounds. It restores the HP of one Pokémon by 200 points.", MEDICINE),
	173: Item.new("Max Potion", "A spray-type medicine for wounds. It completely restores the HP of a single Pokémon.", MEDICINE),
	174: Item.new("Full Restore", "A medicine that fully restores the HP and heals any status problems of a single Pokémon.", MEDICINE),
	175: Item.new("Sacred Ash", "It revives all fainted Pokémon. In doing so, it also fully restores their HP.", MEDICINE),
	176: Item.new("Antidote", "A spray-type medicine. It lifts the effect of poison from one Pokémon.", MEDICINE),
	177: Item.new("Burn Heal", "A spray-type medicine. It heals a single Pokémon that is suffering from a burn.", MEDICINE),
	178: Item.new("Ice Heal", "A spray-type medicine. It defrosts a Pokémon that has been frozen solid.", MEDICINE),
	179: Item.new("Awakening", "A spray-type medicine. It awakens a Pokémon from the clutches of sleep.", MEDICINE),
	180: Item.new("Parlyz Heal", "A spray-type medicine. It eliminates paralysis from a single Pokémon.", MEDICINE),
	181: Item.new("Full Heal", "A spray-type medicine. It heals all the status problems of a single Pokémon.", MEDICINE),
	182: Item.new("Lava Cookie", "Lavaridge Town's local specialty. It heals all the status problems of one Pokémon.", MEDICINE),
	183: Item.new("Old Gateau", "Old Chateau's hidden specialty. It heals all the status problems of a single Pokémon.", MEDICINE),
	184: Item.new("Revive", "A medicine that revives a fainted Pokémon. It restores half the Pokémon's maximum HP.", MEDICINE),
	185: Item.new("Max Revive", "A medicine that revives a fainted Pokémon. It fully restores the Pokémon's HP.", MEDICINE),
	186: Item.new("Berry Juice", "A 100% pure juice made of Berries. It restores the HP of one Pokémon by just 20 points.", MEDICINE),
	187: Item.new("Fresh Water", "Water with a high mineral content. It restores the HP of one Pokémon by 50 points.", MEDICINE),
	188: Item.new("Soda Pop", "A fizzy soda drink. It restores the HP of one Pokémon by 60 points.", MEDICINE),
	189: Item.new("Lemonade", "A very sweet drink. It restores the HP of one Pokémon by 80 points.", MEDICINE),
	190: Item.new("Moomoo Milk", "Milk with a very high nutrition content. It restores the HP of one Pokémon by 100 points.", MEDICINE),
	191: Item.new("EnergyPowder", "A very bitter medicine powder. It restores the HP of one Pokémon by 50 points.", MEDICINE),
	192: Item.new("Energy Root", "A very bitter root. It restores the HP of one Pokémon by 200 points.", MEDICINE),
	193: Item.new("Heal Powder", "A very bitter medicine powder. It heals all the status problems of a single Pokémon.", MEDICINE),
	194: Item.new("Revival Herb", "A very bitter medicinal herb. It revives a fainted Pokémon, fully restoring its HP.", MEDICINE),
	195: Item.new("Ether", "It restores the PP of a Pokémon's selected move by a maximum of 10 points.", MEDICINE),
	196: Item.new("Max Ether", "It fully restores the PP of a single selected move that has been learned by the target Pokémon.", MEDICINE),
	197: Item.new("Elixir", "It restores the PP of all the moves learned by the targeted Pokémon by 10 points each.", MEDICINE),
	198: Item.new("Max Elixir", "It fully restores the PP of all the moves learned by the targeted Pokémon.", MEDICINE),
	199: Item.new("HP Up", "A nutritious drink for Pokémon. It raises the base HP of a single Pokémon.", MEDICINE),
	200: Item.new("Protein", "A nutritious drink for Pokémon. It raises the base Attack stat of a single Pokémon.", MEDICINE),
	201: Item.new("Iron", "A nutritious drink for Pokémon. It raises the base Defense stat of a single Pokémon.", MEDICINE),
	202: Item.new("Carbos", "A nutritious drink for Pokémon. It raises the base Speed stat of a single Pokémon.", MEDICINE),
	203: Item.new("Calcium", "A nutritious drink for Pokémon. It raises the base Sp. Atk (Special Attack) stat of a single Pokémon.", MEDICINE),
	204: Item.new("Zinc", "A nutritious drink for Pokémon. It raises the base Sp. Def (Special Defense) stat of a single Pokémon.", MEDICINE),
	205: Item.new("PP Up", "It slightly raises the maximum PP of a selected move that has been learned by the target Pokémon.", MEDICINE),
	206: Item.new("PP Max", "It maximally raises the top PP of a selected move that has been learned by the target Pokémon.", MEDICINE),
	207: Item.new("Rare Candy", "A candy that is packed with energy. It raises the level of a single Pokémon by one.", MEDICINE),
	208: Item.new("Master Ball", "The best Ball with the ultimate level of performance. It will catch any wild Pokémon without fail.", BALLS),
	209: Item.new("Ultra Ball", "An ultra-performance Ball that provides a higher Pokémon catch rate than a Great Ball.", BALLS),
	210: Item.new("Great Ball", "A good, high-performance Ball that provides a higher Pokémon catch rate than a standard Poké Ball.", BALLS),
	211: Item.new("Poké Ball", "A device for catching wild Pokémon. A capsule system that is thrown like a ball at the target.", BALLS),
	212: Item.new("Safari Ball", "A special Poké Ball that is used only in the Great Marsh. It is decorated in a camouflage pattern.", BALLS),
	213: Item.new("Net Ball", "A somewhat different Poké Ball that works especially well on Water- and Bug-type Pokémon.", BALLS),
	214: Item.new("Dive Ball", "A somewhat different Poké Ball that works especially well on Pokémon that live in the sea.", BALLS),
	215: Item.new("Nest Ball", "A somewhat different Poké Ball that works especially well on weaker Pokémon in the wild.", BALLS),
	216: Item.new("Repeat Ball", "A somewhat different Poké Ball that works especially well on Pokémon species that were previously caught.", BALLS),
	217: Item.new("Timer Ball", "A somewhat different Ball that becomes progressively better the more turns there are in a battle.", BALLS),
	218: Item.new("Luxury Ball", "A comfortable Poké Ball that makes a caught wild Pokémon quickly grow friendly.", BALLS),
	219: Item.new("Premier Ball", "A somewhat rare Poké Ball that has been specially made to commemorate an event of some sort.", BALLS),
	220: Item.new("Dusk Ball", "A somewhat different Poké Ball that can easily catch wild Pokémon at night or in dark places.", BALLS),
	221: Item.new("Heal Ball", "A remedial Poké Ball that restores the caught Pokémon's HP and eliminates any status problem.", BALLS),
	222: Item.new("Quick Ball", "A somewhat different Poké Ball that works better at the start of a wild encounter.", BALLS),
	223: Item.new("Cherish Ball", "A quite rare Poké Ball that has been specially crafted to commemorate an occasion of some sort.", BALLS),
	224: Item.new("Fast Ball", "A Poké Ball that makes it easier to catch Pokémon which are quick to run away.", BALLS),
	225: Item.new("Level Ball", "A Poké Ball for catching Pokémon that are a lower level than your own.", BALLS),
	226: Item.new("Lure Ball", "A Poké Ball for catching Pokémon hooked by a Rod when fishing.", BALLS),
	227: Item.new("Heavy Ball", "A Poké Ball for catching very heavy Pokémon.", BALLS),
	228: Item.new("Love Ball", "A Poké Ball for catching Pokémon that are the opposite gender of your Pokémon.", BALLS),
	229: Item.new("Friend Ball", "A Poké Ball that makes caught Pokémon more friendly.", BALLS),
	230: Item.new("Moon Ball", "A Poké Ball for catching Pokémon that evolve using the Moon Stone.", BALLS),
	231: Item.new("Sport Ball", "A special Poké Ball for the Bug-Catching Contest.", BALLS),
	232: Item.new("Park Ball", "A special Poké Ball for the Pal Park.", BALLS),
	233: Item.new("TM01", "The user focuses its mind before launching this attack. It will fail if the user is hit before it is used.", TMS),
	234: Item.new("TM02", "Sharp, huge claws hook and slash the foe quickly and with great power.", TMS),
	235: Item.new("TM03", "The foe is hit with a pulsing blast of water. It may also confuse the target.", TMS),
	236: Item.new("TM04", "The user quietly focuses its mind and calms its spirit to raise its Sp. Atk and Sp. Def stats.", TMS),
	237: Item.new("TM05", "The foe is scared off, to be replaced by another Pokémon in its party. In the wild, the battle ends.", TMS),
	238: Item.new("TM06", "A move that leaves the foe badly poisoned. This poison damage worsens every turn.", TMS),
	239: Item.new("TM07", "Summons a hailstorm that lasts for five turns. The hailstorm damages all types except Ice.", TMS),
	240: Item.new("TM08", "The user tenses its muscles to bulk up its body, boosting both its Attack and Defense stats.", TMS),
	241: Item.new("TM09", "The user forcefully shoots seeds at the foe. Two to five seeds are shot in rapid succession.", TMS),
	242: Item.new("TM10", "A variable move that changes type and power depending on the hidden ability of the Pokémon using it.", TMS),
	243: Item.new("TM11", "The user intensifies the sun for five turns, powering up Fire-type moves.", TMS),
	244: Item.new("TM12", "The target is taunted into a rage that allows it to use only attack moves for three turns.", TMS),
	245: Item.new("TM13", "The foe is struck with an icy-cold beam of energy. It may also freeze the target solid.", TMS),
	246: Item.new("TM14", "A howling blizzard is summoned to strike the foe. It may also freeze the target solid.", TMS),
	247: Item.new("TM15", "The foe is attacked with a powerful beam. The user must rest on the next turn to regain its energy.", TMS),
	248: Item.new("TM16", "A wondrous wall of light is put up to suppress damage from special attacks for five turns.", TMS),
	249: Item.new("TM17", "It enables the user to evade all attacks. Its chance of failing rises if it is used in succession.", TMS),
	250: Item.new("TM18", "The user summons a heavy rain that falls for five turns, powering up Water-type moves.", TMS),
	251: Item.new("TM19", "A nutrient-draining attack. The user's HP is restored by half the damage taken by the target.", TMS),
	252: Item.new("TM20", "The user creates a protective field that prevents status problems like poison, paralysis, burn, and sleep.", TMS),
	253: Item.new("TM21", "A full-power attack that grows more powerful the less the user likes its Trainer.", TMS),
	254: Item.new("TM22", "A two-turn attack. The user gathers light, then blasts a bundled beam on the second turn.", TMS),
	255: Item.new("TM23", "The foe is slammed with a sturdy tail of steel. It may also lower the target's Defense stat if it hits.", TMS),
	256: Item.new("TM24", "A strong electric blast is loosed at the foe. It may also leave the foe paralyzed.", TMS),
	257: Item.new("TM25", "A wicked thunderbolt is dropped on the foe to inflict damage. It may also leave the target paralyzed.", TMS),
	258: Item.new("TM26", "The user sets off an earthquake that hits all the Pokémon in the battle.", TMS),
	259: Item.new("TM27", "A full-power attack that grows more powerful the more the user likes its Trainer.", TMS),
	260: Item.new("TM28", "The user burrows, then attacks on the second turn. It can also be used to exit dungeons.", TMS),
	261: Item.new("TM29", "The foe is hit by a strong telekinetic force. It may also reduce the foe's Sp. Def stat.", TMS),
	262: Item.new("TM30", "The user hurls a shadowy blob at the foe. It may also lower the foe's Sp. Def stat.", TMS),
	263: Item.new("TM31", "The user attacks with tough fists, etc. It can also break any barrier such as Light Screen and Reflect.", TMS),
	264: Item.new("TM32", "The user begins moving so quickly that it creates illusory copies to raise its evasiveness.", TMS),
	265: Item.new("TM33", "A wondrous wall of light is put up to suppress damage from physical attacks for five turns.", TMS),
	266: Item.new("TM34", "The user strikes the foe with a quick jolt of electricity. This attack cannot be evaded.", TMS),
	267: Item.new("TM35", "The foe is scorched with an intense blast of fire. The target may also be left with a burn.", TMS),
	268: Item.new("TM36", "Unsanitary sludge is hurled at the foe. It may also poison the target.", TMS),
	269: Item.new("TM37", "A five-turn sandstorm is summoned to hurt all combatants except the Rock, Ground, and Steel types.", TMS),
	270: Item.new("TM38", "The foe is attacked with an intense blast of all-consuming fire. It may also leave the target with a burn.", TMS),
	271: Item.new("TM39", "Large boulders are hurled at the foe to inflict damage. It may also make the target flinch.", TMS),
	272: Item.new("TM40", "The user confounds the foe with speed, then strikes. The attack lands without fail.", TMS),
	273: Item.new("TM41", "The user torments and enrages the foe, making it incapable of using the same move twice in a row.", TMS),
	274: Item.new("TM42", "An attack move that doubles its power if the user is poisoned, paralyzed, or has a burn.", TMS),
	275: Item.new("TM43", "An attack move with effects that vary depending on the user's environment.", TMS),
	276: Item.new("TM44", "The user goes to sleep for two turns. It fully restores the user's HP and heals any status problem.", TMS),
	277: Item.new("TM45", "If it is the opposite gender of the user, the foe becomes infatuated and less likely to attack.", TMS),
	278: Item.new("TM46", "The user attacks and steals the foe's held item simultaneously. It can't steal if the user holds an item.", TMS),
	279: Item.new("TM47", "The foe is hit with wings of steel. It may also raise the user's Defense stat.", TMS),
	280: Item.new("TM48", "The user employs its psychic power to exchange abilities with the foe.", TMS),
	281: Item.new("TM49", "The user steals the effects of any healing or status-changing move the foe attempts to use.", TMS),
	282: Item.new("TM50", "The user attacks the foe at full power using fiery energy. It also sharply reduces the user's Sp. Atk.", TMS),
	283: Item.new("TM51", "The user lands and rests its body. It restores the user's HP by up to half of its top HP.", TMS),
	284: Item.new("TM52", "The user attacks at full power. It may also lower the foe's Sp. Def stat if it hits.", TMS),
	285: Item.new("TM53", "The user draws power from nature and fires it at the foe. It may also lower the target's Sp. Def.", TMS),
	286: Item.new("TM54", "A restrained attack that prevents the foe from fainting. The target is left with at least 1 HP.", TMS),
	287: Item.new("TM55", "If the foe's HP is down to under half, this attack will hit with double the power.", TMS),
	288: Item.new("TM56", "The user flings its held item at the foe to attack. Its power and effects depend on the item.", TMS),
	289: Item.new("TM57", "The user attacks with an electric charge. The user uses the remaining electricity to up its Sp. Atk.", TMS),
	290: Item.new("TM58", "The user endures any attack, leaving 1 HP. Its chance of failing rises if it is used in succession.", TMS),
	291: Item.new("TM59", "The foe is attacked with a shock wave generated by the user's gaping mouth.", TMS),
	292: Item.new("TM60", "An energy-draining punch. The user's HP is restored by half the damage taken by the target.", TMS),
	293: Item.new("TM61", "The user shoots a sinister, bluish white flame at the foe to inflict a burn.", TMS),
	294: Item.new("TM62", "The foe is attacked with powdery scales blown by wind. It may also raise all the user's stats.", TMS),
	295: Item.new("TM63", "It prevents the foe from using its held item. Its Trainer is also prevented from using items on it.", TMS),
	296: Item.new("TM64", "The user explodes to inflict damage on all Pokémon in battle. The user faints upon using this move.", TMS),
	297: Item.new("TM65", "The user slashes with a sharp claw made from shadows. It has a high critical-hit ratio.", TMS),
	298: Item.new("TM66", "The user stores power, then attacks. Its power is doubled if used after the foe.", TMS),
	299: Item.new("TM67", "The user recycles a single-use item that has been used in battle so it can be used again.", TMS),
	300: Item.new("TM68", "The user charges the foe using every bit of its power. It must rest on the next turn to recover.", TMS),
	301: Item.new("TM69", "The user polishes its body to reduce drag. It sharply raises the Speed stat.", TMS),
	302: Item.new("TM70", "The user flashes a light that cuts the foe's accuracy. It can also be used to illuminate caves.", TMS),
	303: Item.new("TM71", "The user stabs the foe with a sharpened stone from below. It has a high critical-hit ratio.", TMS),
	304: Item.new("TM72", "An attack move that inflicts double the damage if the user has been hurt by the foe in the same turn.", TMS),
	305: Item.new("TM73", "A weak electric charge is launched at the foe. It causes paralysis if it hits.", TMS),
	306: Item.new("TM74", "The user tackles the foe from a high-speed spin. The slower the user, the greater the damage.", TMS),
	307: Item.new("TM75", "A frenetic dance to uplift the fighting spirit. It sharply raises the user's Attack stat.", TMS),
	308: Item.new("TM76", "The user lays a trap of levitating stones around the foe. The trap hurts foes that switch into battle.", TMS),
	309: Item.new("TM77", "The user hypnotizes itself into copying any stat change made by the foe.", TMS),
	310: Item.new("TM78", "If it is the opposite gender of the user, the foe is charmed into sharply lowering its Sp. Atk stat.", TMS),
	311: Item.new("TM79", "The user releases a horrible aura imbued with dark thoughts. It may also make the target flinch.", TMS),
	312: Item.new("TM80", "Large boulders are hurled at the foe to inflict damage. It may also make the target flinch.", TMS),
	313: Item.new("TM81", "The user slashes at the foe by crossing its scythes or claws as if they were a pair of scissors.", TMS),
	314: Item.new("TM82", "While it is asleep, the user randomly uses one of the moves it knows.", TMS),
	315: Item.new("TM83", "The user draws power from the Berry it is holding to attack. The Berry determines its type and power.", TMS),
	316: Item.new("TM84", "The foe is stabbed with a tentacle or arm seeped with poison. It may also poison the foe.", TMS),
	317: Item.new("TM85", "An attack that works only on a sleeping foe. It absorbs half the damage caused to heal the user's HP.", TMS),
	318: Item.new("TM86", "The user snares the foe with grass and trips it. The heavier the foe, the greater the damage.", TMS),
	319: Item.new("TM87", "The user enrages the foe into confusion. However, it also sharply raises the foe's Attack stat.", TMS),
	320: Item.new("TM88", "The user pecks the foe. If the foe is holding a Berry, the user plucks it and gains its effect.", TMS),
	321: Item.new("TM89", "After making its attack, the user rushes back to switch places with a party Pokémon in waiting.", TMS),
	322: Item.new("TM90", "The user makes a copy of itself using some of its HP. The copy serves as the user's decoy.", TMS),
	323: Item.new("TM91", "The user gathers all its light energy and releases it in one shot. It may also lower the foe's Sp. Def stat.", TMS),
	324: Item.new("TM92", "The user creates a bizarre space in which slower Pokémon get to move first for five turns.", TMS),
	325: Item.new("HM01", "The foe is cut with a scythe or a claw. It can also be used to cut down thin trees.", TMS),
	326: Item.new("HM02", "The user soars, then strikes on the second turn. It can also be used to fly to any familiar town.", TMS),
	327: Item.new("HM03", "It swamps the entire battlefield with a giant wave. It can also be used to cross water.", TMS),
	328: Item.new("HM04", "The foe is slugged with a punch thrown at maximum power. It can also be used to move boulders.", TMS),
	329: Item.new("HM05", "Obstacles are moved, reducing the foe's evasion stat. It can also be used to clear deep fog.", TMS),
	330: Item.new("HM06", "The user slugs the foe with a shattering punch. It can also smash cracked boulders.", TMS),
	331: Item.new("HM07", "The user charges the foe at an awesome speed. It can also be used to climb a waterfall.", TMS),
	332: Item.new("HM08", "Diving on the first turn, the user floats up and attacks on the second turn.", TMS),
	333: Item.new("Cheri Berry", "It may be used or held by a Pokémon to recover from paralysis.", BERRIES),
	334: Item.new("Chesto Berry", "It may be used or held by a Pokémon to recover from sleep.", BERRIES),
	335: Item.new("Pecha Berry", "It may be used or held by a Pokémon to recover from poison.", BERRIES),
	336: Item.new("Rawst Berry", "It may be used or held by a Pokémon to recover from a burn.", BERRIES),
	337: Item.new("Aspear Berry", "It may be used or held by a Pokémon to defrost it.", BERRIES),
	338: Item.new("Leppa Berry", "It may be used or held by a Pokémon to restore a move's PP by 10.", BERRIES),
	339: Item.new("Oran Berry", "It may be used or held by a Pokémon to heal the user by just 10 HP.", BERRIES),
	340: Item.new("Persim Berry", "It may be used or held by a Pokémon to recover from confusion.", BERRIES),
	341: Item.new("Lum Berry", "It may be used or held by a Pokémon to recover from any status problem.", BERRIES),
	342: Item.new("Sitrus Berry", "It may be used or held by a Pokémon to heal the user's HP a little.", BERRIES),
	343: Item.new("Figy Berry", "If held by a Pokémon, it restores the user's HP in a pinch, but may also cause confusion.", BERRIES),
	344: Item.new("Wiki Berry", "If held by a Pokémon, it restores the user's HP in a pinch, but may also cause confusion.", BERRIES),
	345: Item.new("Mago Berry", "If held by a Pokémon, it restores the user's HP in a pinch, but may also cause confusion.", BERRIES),
	346: Item.new("Aguav Berry", "If held by a Pokémon, it restores the user's HP in a pinch, but may also cause confusion.", BERRIES),
	347: Item.new("Iapapa Berry", "If held by a Pokémon, it restores the user's HP in a pinch, but may also cause confusion.", BERRIES),
	348: Item.new("Razz Berry", "Bury it in soft soil to grow a Razz Plant.", BERRIES),
	349: Item.new("Bluk Berry", "Bury it in soft soil to grow a Bluk Plant.", BERRIES),
	350: Item.new("Nanab Berry", "Bury it in soft soil to grow a Nanab Plant.", BERRIES),
	351: Item.new("Wepear Berry", "Bury it in soft soil to grow a Wepear Plant.", BERRIES),
	352: Item.new("Pinap Berry", "Bury it in soft soil to grow a Pinap Plant.", BERRIES),
	353: Item.new("Pomeg Berry", "Using it on a Pokémon makes it more friendly, but it also lowers its base HP.", BERRIES),
	354: Item.new("Kelpsy Berry", "Using it on a Pokémon makes it more friendly, but it also lowers its base Attack stat.", BERRIES),
	355: Item.new("Qualot Berry", "Using it on a Pokémon makes it more friendly, but it also lowers its base Defense stat.", BERRIES),
	356: Item.new("Hondew Berry", "Using it on a Pokémon makes it more friendly, but it also lowers its base Sp. Atk stat.", BERRIES),
	357: Item.new("Grepa Berry", "Using it on a Pokémon makes it more friendly, but it also lowers its base Sp. Def stat.", BERRIES),
	358: Item.new("Tamato Berry", "Using it on a Pokémon makes it more friendly, but it also lowers its base Speed stat.", BERRIES),
	359: Item.new("Cornn Berry", "Bury it in soft soil to grow a Cornn Plant.", BERRIES),
	360: Item.new("Magost Berry", "Bury it in soft soil to grow a Magost Plant.", BERRIES),
	361: Item.new("Rabuta Berry", "Bury it in soft soil to grow a Rabuta Plant.", BERRIES),
	362: Item.new("Nomel Berry", "Bury it in soft soil to grow a Nomel Plant.", BERRIES),
	363: Item.new("Spelon Berry", "Bury it in soft soil to grow a Spelon Plant.", BERRIES),
	364: Item.new("Pamtre Berry", "Bury it in soft soil to grow a Pamtre Plant.", BERRIES),
	365: Item.new("Watmel Berry", "Bury it in soft soil to grow a Watmel Plant.", BERRIES),
	366: Item.new("Durin Berry", "Bury it in soft soil to grow a Durin Plant.", BERRIES),
	367: Item.new("Belue Berry", "Bury it in soft soil to grow a Belue Plant.", BERRIES),
	368: Item.new("Occa Berry", "If held by a Pokémon, it weakens a foe's supereffective Fire-type attack.", BERRIES),
	369: Item.new("Passho Berry", "If held by a Pokémon, it weakens a foe's supereffective Water-type attack.", BERRIES),
	370: Item.new("Wacan Berry", "If held by a Pokémon, it weakens a foe's supereffective Electric-type attack.", BERRIES),
	371: Item.new("Rindo Berry", "If held by a Pokémon, it weakens a foe's supereffective Grass-type attack.", BERRIES),
	372: Item.new("Yache Berry", "If held by a Pokémon, it weakens a foe's supereffective Ice-type attack.", BERRIES),
	373: Item.new("Chople Berry", "If held by a Pokémon, it weakens a foe's supereffective Fighting-type attack.", BERRIES),
	374: Item.new("Kebia Berry", "If held by a Pokémon, it weakens a foe's supereffective Poison-type attack.", BERRIES),
	375: Item.new("Shuca Berry", "If held by a Pokémon, it weakens a foe's supereffective Ground-type attack.", BERRIES),
	376: Item.new("Coba Berry", "If held by a Pokémon, it weakens a foe's supereffective Flying-type attack.", BERRIES),
	377: Item.new("Payapa Berry", "If held by a Pokémon, it weakens a foe's supereffective Psychic-type attack.", BERRIES),
	378: Item.new("Tanga Berry", "If held by a Pokémon, it weakens a foe's supereffective Bug-type attack.", BERRIES),
	379: Item.new("Charti Berry", "If held by a Pokémon, it weakens a foe's supereffective Rock-type attack.", BERRIES),
	380: Item.new("Kasib Berry", "If held by a Pokémon, it weakens a foe's supereffective Ghost-type attack.", BERRIES),
	381: Item.new("Haban Berry", "If held by a Pokémon, it weakens a foe's supereffective Dragon-type attack.", BERRIES),
	382: Item.new("Colbur Berry", "If held by a Pokémon, it weakens a foe's supereffective Dark-type attack.", BERRIES),
	383: Item.new("Babiri Berry", "If held by a Pokémon, it weakens a foe's supereffective Steel-type attack.", BERRIES),
	384: Item.new("Chilan Berry", "If held by a Pokémon, it weakens a foe's Normal-type attack.", BERRIES),
	385: Item.new("Liechi Berry", "If held by a Pokémon, it raises its Attack stat in a pinch.", BERRIES),
	386: Item.new("Ganlon Berry", "If held by a Pokémon, it raises its Defense stat in a pinch.", BERRIES),
	387: Item.new("Salac Berry", "If held by a Pokémon, it raises its Speed stat in a pinch.", BERRIES),
	388: Item.new("Petaya Berry", "If held by a Pokémon, it raises its Sp. Atk stat in a pinch.", BERRIES),
	389: Item.new("Apicot Berry", "If held by a Pokémon, it raises its Sp. Def stat in a pinch.", BERRIES),
	390: Item.new("Lansat Berry", "If held by a Pokémon, it raises its critical-hit ratio in a pinch.", BERRIES),
	391: Item.new("Starf Berry", "If held by a Pokémon, it sharply raises one of its stats in a pinch.", BERRIES),
	392: Item.new("Enigma Berry", "If held by a Pokémon, it restores its HP if it is hit by a foe's supereffective attack.", BERRIES),
	393: Item.new("Micle Berry", "If held by a Pokémon, it raises the accuracy of a move just once in a pinch.", BERRIES),
	394: Item.new("Custap Berry", "If held by a Pokémon, it gets to move first just once in a pinch.", BERRIES),
	395: Item.new("Jaboca Berry", "If held by a Pokémon, and if a foe's physical attack lands, the foe also takes damage.", BERRIES),
	396: Item.new("Rowap Berry", "If held by a Pokémon, and if a foe's special attack lands, the foe also takes damage.", BERRIES),
	397: Item.new("Orange Mail", "A piece of mail featuring a cute Zigzagoon print. It is to be held by a Pokémon.", ITEMS),
	398: Item.new("Harbor Mail", "A piece of mail featuring a cute Wingull print. It is to be held by a Pokémon.", ITEMS),
	399: Item.new("Glitter Mail", "A piece of mail featuring a cute Pikachu print. It is to be held by a Pokémon.", ITEMS),
	400: Item.new("Mech Mail", "A piece of mail featuring a cute Magnemite print. It is to be held by a Pokémon.", ITEMS),
	401: Item.new("Wood Mail", "A piece of mail featuring a cute Slakoth print. It is to be held by a Pokémon.", ITEMS),
	402: Item.new("Wave Mail", "A piece of mail featuring a cute Wailmer print. It is to be held by a Pokémon.", ITEMS),
	403: Item.new("Bead Mail", "A piece of mail to be held by a Pokémon. It will bear the print of the Pokémon holding it.", ITEMS),
	404: Item.new("Shadow Mail", "A piece of mail featuring a cute Duskull print. It is to be held by a Pokémon.", ITEMS),
	405: Item.new("Tropic Mail", "A piece of mail featuring a cute Bellossom print. It is to be held by a Pokémon.", ITEMS),
	406: Item.new("Dream Mail", "A piece of mail to be held by a Pokémon. It will bear the print of the Pokémon holding it.", ITEMS),
	407: Item.new("Fab Mail", "A piece of mail featuring a gorgeous, extravagant print. It is to be held by a Pokémon.", ITEMS),
	408: Item.new("Retro Mail", "A piece of mail featuring a print of three cute Pokémon. It is to be held by a Pokémon.", ITEMS),
	409: Item.new("X Attack", "An item that raises the Attack stat of a Pokémon in battle. It wears off if the Pokémon is withdrawn.", BATTLE_ITEMS),
	410: Item.new("X Defend", "An item that raises the Defense of a Pokémon in battle. It wears off if the Pokémon is withdrawn.", BATTLE_ITEMS),
	411: Item.new("X Special", "An item that raises the Sp. Atk stat of a Pokémon in battle. It wears off if the Pokémon is withdrawn.", BATTLE_ITEMS),
	412: Item.new("X Sp. Def", "An item that raises the Sp. Def stat of a Pokémon in battle. It wears off if the Pokémon is withdrawn.", BATTLE_ITEMS),
	413: Item.new("X Speed", "An item that raises the Speed stat of a Pokémon in battle. It wears off if the Pokémon is withdrawn.", BATTLE_ITEMS),
	414: Item.new("X Accuracy", "An item that raises the accuracy of a Pokémon in battle. It wears off if the Pokémon is withdrawn.", BATTLE_ITEMS),
	415: Item.new("Dire Hit", "An item that raises the critical-hit ratio of a Pokémon in battle.", BATTLE_ITEMS),
	416: Item.new("Guard Spec.", "An item that prevents stat reduction among the Trainer's party Pokémon for five turns after use.", BATTLE_ITEMS),
	417: Item.new("Poké Doll", "A doll that attracts Pokémon. Use it to flee from any battle with a wild Pokémon.", BATTLE_ITEMS),
	418: Item.new("Fluffy Tail", "An item that attracts Pokémon. Use it to flee from any battle with a wild Pokémon.", BATTLE_ITEMS),
	419: Item.new("Blue Flute", "A blue flute made from blown glass. Its melody awakens a single Pokémon from sleep.", BATTLE_ITEMS),
	420: Item.new("Yellow Flute", "A yellow flute made from blown glass. Its melody snaps a single Pokémon out of confusion.", BATTLE_ITEMS),
	421: Item.new("Red Flute", "A red flute made from blown glass. Its melody snaps a single Pokémon out of infatuation.", BATTLE_ITEMS),
	422: Item.new("Bicycle", "A folding Bicycle that enables much faster movement than the Running Shoes.", KEY_ITEMS),
	423: Item.new("Old Rod", "An old and beat-up fishing rod. Use it by any body of water to fish for wild aquatic Pokémon.", KEY_ITEMS),
	424: Item.new("Good Rod", "A new, good-quality fishing rod. Use it by any body of water to fish for wild aquatic Pokémon.", KEY_ITEMS),
	425: Item.new("Super Rod", "An awesome, high-tech fishing rod. Use it by any body of water to fish for wild aquatic Pokémon.", KEY_ITEMS),
	426: Item.new("Dowsing MCHN", "It checks for unseen items in the area and makes noise and lights when it finds something.", KEY_ITEMS),
	427: Item.new("TM96", "The user creates shockwaves to attack the target. This attack does physical damage.", TMS),
	428: Item.new("Town Map", "A very convenient map that can be viewed anytime. It even shows your present location.", KEY_ITEMS),
	429: Item.new("Coin Case", "A case for holding Coins obtained at the Game Corner. It holds up to 99,999 Coins.", KEY_ITEMS),
	430: Item.new("Gracidea", "A flower sometimes bundled in bouquets to convey gratitude on special occasions like birthdays.", KEY_ITEMS),
	431: Item.new("Soot Sack", "A sack used to gather and hold volcanic ash.", KEY_ITEMS),
	432: Item.new("Explorer Kit", "A bag filled with convenient tools for exploring. It provides access to the Underground.", KEY_ITEMS),
	433: Item.new("Loot Sack", "A sturdy, spacious bag that is used to carry loot obtained in the coal mine.", KEY_ITEMS),
	434: Item.new("Rule Book", "It lists the rules for holding battles. For linked battles, you may choose which rules to use.", KEY_ITEMS),
	435: Item.new("Point Card", "A card that lists the Battle Points you have earned.", KEY_ITEMS),
	436: Item.new("Journal", "A notebook that keeps a day-to-day record of your adventure so far.", KEY_ITEMS),
	437: Item.new("Seal Case", "A case for storing Seals that can be applied to the capsule cases of Poké Balls.", KEY_ITEMS),
	438: Item.new("Fashion Case", "A fancy case for the tidy and organized storage of colorful Pokémon Accessories.", KEY_ITEMS),
	439: Item.new("Seal Bag", "A tiny bag that can hold ten Seals for decorating Poké Balls.", KEY_ITEMS),
	440: Item.new("Pal Pad", "A convenient notepad that is used for registering your friends and keeping a record of game play.", KEY_ITEMS),
	441: Item.new("Works Key", "A large key for operating the doors of the Valley Windworks. It was held by a Team Galactic Grunt.", KEY_ITEMS),
	442: Item.new("Old Charm", "An ancient good-luck charm made of Pokémon bones to be taken to the elder of Celestic Town.", KEY_ITEMS),
	443: Item.new("Galactic Key", "A card key for disengaging security systems in the Galactic HQ. Losing it can result in punishment, apparently.", KEY_ITEMS),
	444: Item.new("Red Chain", "A mythical chain that is said to link the legendary Pokémon that created the Sinnoh region.", KEY_ITEMS),
	445: Item.new("Sprayduck", "A watering can shaped like a Psyduck. It helps promote healthy growth of planted Berries.", KEY_ITEMS),
	446: Item.new("Poffin Case", "A case for storing Poffin cooked from Berries.", KEY_ITEMS),
	447: Item.new("Suite Key", "A key to one of the suites at the luxury hotel by a lake. For some odd reason, it often disappears.", KEY_ITEMS),
	448: Item.new("Oak's Letter", "A letter from Prof. Oak. Written in it is a request for you to go to Rt. 224.", KEY_ITEMS),
	449: Item.new("Lunar Wing", "A feather that glows like the moon. It is said to possess the power to dispel nightmares.", KEY_ITEMS),
	450: Item.new("Member Card", "A card needed for entering the inn in Canalave City. Oddly, the last date marked on it was 50 years ago.", KEY_ITEMS),
	451: Item.new("Azure Flute", "A flute that puts out echoing sounds that do not seem to be of this world. It is unknown who made it.", KEY_ITEMS),
	452: Item.new("BBFerry Ticket", "The ticket required for sailing on the ferry on Bealbeach Lake. It has a drawing of a ship on it.", KEY_ITEMS),
	453: Item.new("Contest Pass", "The pass required for entering Pokémon Contests. It has a drawing of an award ribbon on it.", KEY_ITEMS),
	454: Item.new("Magma Stone", "A stone formed when boulders melted in intensely hot magma. Magma remains sealed inside.", KEY_ITEMS),
	455: Item.new("Parcel", "A parcel that you are supposed to deliver to your childhood friend who left Twinleaf Town.", KEY_ITEMS),
	456: Item.new("Coupon 1", "A coupon to be exchanged for a Pokémon Watch (Pokétch for short). Three coupons are needed.", KEY_ITEMS),
	457: Item.new("Coupon 2", "A coupon to be exchanged for a Pokémon Watch (Pokétch for short). Three coupons are needed.", KEY_ITEMS),
	458: Item.new("Coupon 3", "A coupon to be exchanged for a Pokémon Watch (Pokétch for short). Three coupons are needed.", KEY_ITEMS),
	459: Item.new("Storage Key", "The key to Team Galactic's sinister warehouse located at the edge of Veilstone City.", KEY_ITEMS),
	460: Item.new("SecretPotion", "A fantastic medicine dispensed by the pharmacy in Cianwood City. It fully heals a Pokémon of any ailment.", KEY_ITEMS),
	461: Item.new("Vs. Seeker", "A device that indicates Trainers who want to battle. Its battery charges while you walk.", KEY_ITEMS),
	462: Item.new("Vs. Recorder", "An amazing device that can record a battle either between friends or at a special battle facility.", KEY_ITEMS),
	463: Item.new("Secret Key", "A high-tech key to be used at a specific location. It emits a special electric signal to open a door.", KEY_ITEMS),
	464: Item.new("Apricorn Box", "A handy box where you can store up to 99 Apricorns of each kind.", KEY_ITEMS),
	465: Item.new("Unown Report", "A report of all the discovered kinds of Unown.", KEY_ITEMS),
	466: Item.new("Berry Pots", "Handy containers for cultivating Berries wherever you go.", KEY_ITEMS),
	467: Item.new("Blue Card", "A card to save points for the Buena's Password show.", KEY_ITEMS),
	468: Item.new("SlowpokeTail", "A very tasty tail of something. It sells for a high price.", KEY_ITEMS),
	469: Item.new("Clear Bell", "A very old-fashioned bell that makes a gentle ringing.", KEY_ITEMS),
	470: Item.new("Card Key", "A card key that opens a shutter in the Radio Tower.", KEY_ITEMS),
	471: Item.new("Basement Key", "A key that opens a door in the Goldenrod Tunnel.", KEY_ITEMS),
	472: Item.new("Squirtbottle", "A bottle used for watering plants in the Berry Pots.", KEY_ITEMS),
	473: Item.new("Red Scale", "A scale from the red Gyarados. It glows red like a flame.", KEY_ITEMS),
	474: Item.new("Lost Item", "The Poké Doll lost by the Copycat.", KEY_ITEMS),
	475: Item.new("Pass", "A ticket to ride the Magnet Train, whenever and however much you like.", KEY_ITEMS),
	476: Item.new("Machine Part", "An important machine part for the Power Plant that was stolen.", KEY_ITEMS),
	477: Item.new("Silver Wing", "A strange, silvery feather that sparkles.", KEY_ITEMS),
	478: Item.new("Rainbow Wing", "A mystical rainbow feather that sparkles.", KEY_ITEMS),
	479: Item.new("Mystery Egg", "A mysterious Egg obtained from Mr. Pokémon. What's in the Egg is unknown.", KEY_ITEMS),
	480: Item.new("Photo Album", "A nice photo album for storing all the photos taken along your adventure.", KEY_ITEMS),
	481: Item.new("GB Sounds", "A music player that allows you to listen to nostalgic songs. It's operated with a single switch.", KEY_ITEMS),
	482: Item.new("Tidal Bell", "A very old-fashioned bell that makes a gentle ringing.", KEY_ITEMS),
	483: Item.new("RageCandyBar", "A famous candy in Mahogany Town. Many tourists like to buy them to take home.", KEY_ITEMS),
	484: Item.new("Jade Orb", "A shiny green orb that is said to have a legend and has a deep connection with the Hoenn region.", KEY_ITEMS),
	485: Item.new("Lock Capsule", "A sturdy Capsule that can only be opened with a special key.", KEY_ITEMS),
	486: Item.new("Red Orb", "A shiny red orb that is said to have a legend and has a deep connection with the Hoenn region.", KEY_ITEMS),
	487: Item.new("Blue Orb", "A shiny blue orb that is said to have a legend and has a deep connection with the Hoenn region.", KEY_ITEMS),
	488: Item.new("Enigma Stone", "A crystal ball from an excavation. A very beautiful stone that is covered with bits of rock and earth.", KEY_ITEMS),
	489: Item.new("Silph Scope", "A scope that makes unseeable Pokémon visible.  It is made by Silph Co.", KEY_ITEMS),
	490: Item.new("LAB KEY", "This is a custom Key Item.", BERRIES),
	491: Item.new("Poké Radar", "A tool that can search out Pokémon that are hiding in grass. Its battery is recharged as you walk.", KEY_ITEMS),
	492: Item.new("Sticker Case", "This device helps you find a defeated wild Pokemon more easily.", KEY_ITEMS),
	493: Item.new("Atom Ball", "A special Poké Ball created to contain Urayne. You should not have this.", BALLS),
	494: Item.new("T.U.R Ticket", "A ticket for the Tandor Underground Railway.", KEY_ITEMS),
	495: Item.new("PST", "Pokémon Speech Translator. Can help you understand some Pokémon. It's still a prototype.", KEY_ITEMS),
	496: Item.new("Coconut Milk", "Fresh Coconut milk. Heals 50 HP and cures status effects.", MEDICINE),
	497: Item.new("Jungle's Crown", "An item to be held by a Pokémon. It belongs to the king of the jungle. Boosts Fighting attacks.", ITEMS),
	498: Item.new("Royal Jelly", "An item to be held by a Pokémon. A mysterious goo left behind by Seikamater.", ITEMS),
	499: Item.new("Bug Spray", "Bug spray. Works better than any Repel to get bugs scurrying!", KEY_ITEMS),
	500: Item.new("Acai Berry", "It may be used or held by a Pokémon to recover from paralysis.", BERRIES),
	501: Item.new("Bacu Berry", "It may be used or held by a Pokémon to recover from sleep.", BERRIES),
	502: Item.new("Cupu Berry", "It may be used or held by a Pokémon to recover from a burn.", BERRIES),
	503: Item.new("Guara Berry", "It may be used or held by a Pokémon to defrost it.", BERRIES),
	504: Item.new("Hair Fossil", "A fossil of an ancient Pokémon that lived in the Mountains. It appears to be a wisp of Hair.", ITEMS),
	505: Item.new("Tusk Fossil", "A fossil of an ancient Pokémon that lived in the Plains. It appears to be part of a Tusk.", ITEMS),
	506: Item.new("Moss Shard", "An item to be held by a Pokémon. It is a seed imbued with life that ups the power of Grass-type moves.", ITEMS),
	507: Item.new("Ice Shard", "An item to be held by a Pokémon. It is a piece of ice that repels heat and boosts Ice-type moves.", ITEMS),
	508: Item.new("Pretty Ribbon", "An item to be held by a Pokémon. It is an elegant pink ribbon that boosts Fairy-type moves.", ITEMS),
	509: Item.new("Mega Bracelet", "This bracelet contains an untold power that somehow enables Pokémon carrying a Mega Stone to Mega Evolve in battle.", KEY_ITEMS),
	510: Item.new("Metalynxite", "One variety of the mysterious Mega Stones. Have Metalynx hold it, and this stone will enable it to Mega Evolve during battle.", ITEMS),
	511: Item.new("Archillesite", "One variety of the mysterious Mega Stones. Have Archilles hold it, and this stone will enable it to Mega Evolve during battle.", ITEMS),
	512: Item.new("Electruxolite", "One variety of the mysterious Mega Stones. Have Electruxo hold it, and this stone will enable it to Mega Evolve during battle.", ITEMS),
	513: Item.new("Gyaradosite", "One variety of the mysterious Mega Stones. Have Gyarados hold it, and this stone will enable it to Mega Evolve in battle.", ITEMS),
	514: Item.new("Ampharosite", "One variety of the mysterious Mega Stones. Have Ampharos hold it, and this stone will enable it to Mega Evolve in battle.", ITEMS),
	515: Item.new("Baariettite", "One variety of the mysterious Mega Stones. Have Baariette hold it, and this stone will enable it to Mega Evolve during battle.", ITEMS),
	516: Item.new("Drilgannite", "One variety of the mysterious Mega Stones. Have Drilgann hold it, and this stone will enable it to Mega Evolve during battle.", ITEMS),
	517: Item.new("Sableyeite", "One variety of the mysterious Mega Stones. Have Sableye hold it, and this stone will enable it to Mega Evolve during battle.", ITEMS),
	518: Item.new("Inflagetite", "One variety of the mysterious Mega Stones. Have Inflagetah hold it, and this stone will enable it to Mega Evolve during battle.", ITEMS),
	519: Item.new("Dramsamaite", "One variety of the mysterious Mega Stones. Have Dramsama hold it, and this stone will enable it to Mega Evolve during battle.", ITEMS),
	520: Item.new("Daikatunite", "One variety of the mysterious Mega Stones. Have Daikatuna hold it, and this stone will enable it to Mega Evolve during battle.", ITEMS),
	521: Item.new("TM93", "The target is infested and attacked for four to five turns. The target can't flee during this time.", TMS),
	522: Item.new("TM94", "The user damages opposing Pokémon by emitting a powerful flash.", TMS),
	523: Item.new("Bike Wheel", "This bike wheel can be used to fix a bicycle.", KEY_ITEMS),
	524: Item.new("Carrot Wine", "Delicious Carrot Wine, be careful to not drink too much! Heals 100 HP and cures status effects.", MEDICINE),
	525: Item.new("Secret Note", "You don't know who gave you this. It says that the password is 092.", KEY_ITEMS),
	526: Item.new("Syrentideite", "One variety of the mysterious Mega Stones. Have Syrentide hold it, and this stone will enable it to Mega Evolve during battle.", ITEMS),
	527: Item.new("Unidentified Fallen Object", "One variety of the mysterious Mega Stones. Have s51-A hold it, and this stone will enable it to Mega Evolve during battle.", ITEMS),
	528: Item.new("TM95", "The user damages opposing Pokémon and lowers it's defense and special defense.", TMS),
	529: Item.new("Boxing Gloves", "This device given to you by the Tinkerer allows you to easily smash rugged rocks in your way.", KEY_ITEMS),
	530: Item.new("Eviolite", "A mysterious evolutionary lump. When held, it raises the Defense and Sp. Def of a Pokémon that can still evolve.", ITEMS),
	531: Item.new("Fire Gem", "A gem with an essence of fire. When held, it strengthens the power of a Fire-type move only once.", ITEMS),
	532: Item.new("Water Gem", "A gem with an essence of water. When held, it strengthens the power of a Water-type move only once.", ITEMS),
	533: Item.new("Electric Gem", "A gem with an essence of electricity. When held, it strengthens the power of an Electric-type move only once.", ITEMS),
	534: Item.new("Grass Gem", "A gem with an essence of nature. When held, it strengthens the power of a Grass-type move only once.", ITEMS),
	535: Item.new("Ice Gem", "A gem with an essence of ice. When held, it strengthens the power of an Ice-type move only once.", ITEMS),
	536: Item.new("Fighting Gem", "A gem with an essence of combat. When held, it strengthens the power of a Fighting-type move only once.", ITEMS),
	537: Item.new("Poison Gem", "A gem with an essence of poison. When held, it strengthens the power of a Poison-type move only once.", ITEMS),
	538: Item.new("Ground Gem", "A gem with an essence of land. When held, it strengthens the power of a Ground-type move only once.", ITEMS),
	539: Item.new("Flying Gem", "A gem with an essence of air. When held, it strengthens the power of a Flying-type move only once.", ITEMS),
	540: Item.new("Psychic Gem", "A gem with an essence of the mind. When held, it strengthens the power of a Psychic-type move only once.", ITEMS),
	541: Item.new("Bug Gem", "A gem with an insect-like essence. When held, it strengthens the power of a Bug-type move only once.", ITEMS),
	542: Item.new("Rock Gem", "A gem with an essence of rock. When held, it strengthens the power of a Rock-type move only once.", ITEMS),
	543: Item.new("Ghost Gem", "A gem with a spectral essence. When held, it strengthens the power of a Ghost-type move only once.", ITEMS),
	544: Item.new("Dragon Gem", "A gem with a draconic essence. When held, it strengthens the power of a Dragon-type move only once.", ITEMS),
	545: Item.new("Dark Gem", "A gem with an essence of darkness. When held, it strengthens the power of a Dark-type move only once.", ITEMS),
	546: Item.new("Steel Gem", "A gem with an essence of steel. When held, it strengthens the power of a Steel-type move only once.", ITEMS),
	547: Item.new("Normal Gem", "A gem with an ordinary essence. When held, it strengthens the power of a Normal-type move only once.", ITEMS),
	548: Item.new("Whimsicottite", "One variety of the mysterious Mega Stones. Have Whimsicott hold it, and this stone will enable it to Mega Evolve during battle.", ITEMS),
	549: Item.new("Arbokite", "One variety of the mysterious Mega Stones. Have Arbok hold it, and this stone will enable it to Mega Evolve during battle.", ITEMS),
	550: Item.new("Yoshitaka's Letter", "A letter from the great Yoshitaka, show it to his grandsons.", KEY_ITEMS),
	551: Item.new("Rocky Helmet", "If the holder of this item takes damage, the attacker will also be damaged upon contact.", ITEMS),
	552: Item.new("Eject Button", "If the holder is hit by an attack, it will switch with another Pokémon in your party.", ITEMS),
	553: Item.new("Red Card", "A card with a mysterious power. When the holder is struck by a foe, the attacker is removed from battle.", ITEMS),
	554: Item.new("Float Stone", "A very light stone. It reduces the weight of a Pokémon when held.", ITEMS),
	555: Item.new("Binding Band", "A band that increases the power of binding moves when held.", ITEMS),
	556: Item.new("Absorb Bulb", "A consumable bulb. If the holder is hit by a Water-type move, its Sp. Atk will rise.", ITEMS),
	557: Item.new("Cell Battery", "A consumable battery. If the holder is hit by an Electric-type move, its Attack will rise.", ITEMS),
	558: Item.new("Ring Target", "Moves that would otherwise have no effect will land on the Pokémon that holds it.", ITEMS),
	559: Item.new("Air Balloon", "When held by a Pokémon, the Pokémon will float into the air. When the holder is attacked, this item will burst.", ITEMS),
	560: Item.new("Assault Vest", "An item to be held by a Pokémon. This offensive vest raises Sp. Def but prevents the use of status moves.", ITEMS),
	561: Item.new("Fairy Gem", "A gem with an essence of nature. When held, it strengthens the power of a Fairy-type move one time.", ITEMS),
	562: Item.new("Prison Bottle", "A bottle believed to have been used to seal away the power of a certain Pokémon long, long ago.", KEY_ITEMS),
	563: Item.new("Luminous Moss", "An item to be held by a Pokémon. It boosts Sp. Def if hit with a Water-type attack. It can only be used once.", ITEMS),
	564: Item.new("Weakness Policy", "An item to be held by a Pokémon. Attack and Sp. Atk sharply increase if the holder is hit with a move it's weak to.", ITEMS),
	565: Item.new("Pixie Plate", "An item to be held by a Pokémon. It is a stone tablet that boosts the power of Fairy-type moves.", ITEMS),
	566: Item.new("Roseli Berry", "Weakens a supereffective Fairy-type attack against the holding Pokémon.", BERRIES),
	567: Item.new("Kee Berry", "If held by a Pokémon, this Berry will increase the Pokémon's Defense stat when hit by a physical attack.", BERRIES),
	568: Item.new("Maranga Berry", "If held by a Pokémon, this Berry will increase the Pokémon's Special Defense stat when hit by a special attack.", BERRIES),
	569: Item.new("Snowball", "An item to be held by a Pokémon. It boosts Attack if hit with an Ice-type attack. It can only be used once.", ITEMS),
	570: Item.new("Safety Goggles", "An item to be held by a Pokémon. These goggles protect the holder from both weather-related damage and powder.", ITEMS),
	571: Item.new("Hafli Berry", "If held by a Pokémon, it weakens a foe's supereffective Nuclear-type attack.", BERRIES),
	572: Item.new("Kellyn's Letter", "A letter from Kellyn. Deliver it to Cameron on the Power Plant Island.", KEY_ITEMS),
	573: Item.new("Burnt Notebook", "A burnt notebook found in the power plant, it's pages seem to be scattered about.", KEY_ITEMS),
	574: Item.new("Rusty Key", "A rusty key found in the power plant.", KEY_ITEMS),
	575: Item.new("Power Glove", "This device given to you by the Tinkerer allows you to push boulders on your own as if you had super-strength.", KEY_ITEMS),
	576: Item.new("Nuclear Ball", "A new kind of Poké Ball that works especially well on Nuclear-type Pokémon.", BALLS),
	577: Item.new("Sachet", "A sachet filled with fragrant perfumes that are just slightly too overwhelming. Yet it's loved by a certain Pokémon.", ITEMS),
	578: Item.new("Power Cell", "A power cell used to power up advanced electrical equipments.", KEY_ITEMS),
	579: Item.new("Maria's Key", "A key given by a creepy guy that unlocks Gym Leader Maria's house.", KEY_ITEMS),
	580: Item.new("Oval Charm", "An oval charm said to increase the chance of Eggs being found at the Day Care.", KEY_ITEMS),
	581: Item.new("Shiny Charm", "A shiny charm said to increase the chance of finding a Shiny Pokémon.", KEY_ITEMS),
	582: Item.new("Aromatic Herb", "A herb filled with fragrant perfumes that are just slightly too overwhelming. Yet it's loved by a certain Pokémon.", ITEMS),
	583: Item.new("Air Mail", "Stationery featuring a print of colorful letter sets. Let a Pokémon hold it for delivery.", ITEMS),
	584: Item.new("Gengarite", "One of the mysterious Mega Stones. Have Gengar hold it, and this stone will enable it to Mega Evolve in battle.", ITEMS),
	585: Item.new("Uranium Core", "Concentrated nuclear fuel used to power Nuclear Plants.", KEY_ITEMS),
	586: Item.new("Kiricornite", "One of the mysterious Mega Stones. Have Kiricorn hold it, and this stone will enable it to Mega Evolve in battle.", ITEMS),
	587: Item.new("Gold Fossil", "A fossil of an ancient Pokémon that lived in Islands. It appears to be a golden bone.", ITEMS),
	588: Item.new("TM97", "The user chomps hard on the target with its sharp front fangs. It cuts the target's HP to half.", TMS),
	589: Item.new("TM98", "This move can be used only after the user has used all the other moves it knows in the battle.", TMS),
	590: Item.new("TM99", "An attack move that cuts down the target's HP to equal the user's HP.", TMS),
	591: Item.new("TM100", "The user focuses its willpower to its head and attacks the foe. It may also make the target flinch.", TMS),
	592: Item.new("Surfboard", "This device given to you by the Tinkerer makes it possible to surf on water without the help of a Pokémon. Cowabunga!", KEY_ITEMS),
	593: Item.new("Scuba Gear", "This device given to you by the Tinkerer allows you to dive underwater on your own. Who ever used Dive anyways?", KEY_ITEMS),
	594: Item.new("Climbing Pick", "This device given to you by the Tinkerer allows you to climb up waterfalls while using your surfboard. Extreme sports are fun!", KEY_ITEMS),
	595: Item.new("Rich Mulch", "A plant fertilizer. It increases Berry harvest without the need for particularly diligent care.", BERRIES),
	596: Item.new("Sprinklotad", "A watering can shaped like a Lotad. It helps promote healthy growth of planted Berries.", KEY_ITEMS),
	597: Item.new("Quadcopter", "Final device created by the Tinkerer. Use this remote-controlled drone to Fly anywhere without the help of a Pokémon!", KEY_ITEMS),
	598: Item.new("Ferry Pass", "A Frequent Sailor card for the Venesi Ferry to Bealbeach and Silverport.", KEY_ITEMS),
	599: Item.new("Dark Dramsamaite", "A disturbing variety of the mysterious Mega Stones. Have Dramsama hold it, and this stone will enable it to Mega Evolve during battle.", ITEMS),
	600: Item.new("Map Scrap 1", "A torn piece of an ancient sea map. This item refers to a quest that is not yet implemented.", KEY_ITEMS),
	601: Item.new("Map Scrap 2", "A torn piece of an ancient sea map. This item refers to a quest that is not yet implemented.", KEY_ITEMS),
	602: Item.new("Map Scrap 3", "A torn piece of an ancient sea map. This item refers to a quest that is not yet implemented.", KEY_ITEMS),
	603: Item.new("Map Scrap 4", "A torn piece of an ancient sea map. This item refers to a quest that is not yet implemented.", KEY_ITEMS),
	604: Item.new("Map Scrap 5", "A torn piece of an ancient sea map. This item refers to a quest that is not yet implemented.", KEY_ITEMS),
	605: Item.new("Map Scrap 6", "A torn piece of an ancient sea map. This item refers to a quest that is not yet implemented.", KEY_ITEMS),
	606: Item.new("Exp. All", "Turning on this special device will allow all the Pokémon on your team to receive Exp. Points from battles.", KEY_ITEMS),
	607: Item.new("Oblivicornite", "One of the mysterious Mega Stones. Have Oblivicorn hold it, and this stone will enable it to Mega Evolve in battle.", ITEMS),
}


var tm_hm_database = {
	"TM27" : "Return"
}

func get_item_by_id(id: int):
	var item = item_list.get(id)
	if item == null:
		push_error("Item id not found in database: " + str(id))
		return null
	item.id = id
	return item

func get_id_by_name(_name: String):
	for key in item_list.keys():
		if item_list.get(key).name == _name:
			return key
	push_error("Item name not found in database: " + _name)
	return -1

func get_item_by_name(_name: String):
	var id = get_id_by_name(_name)
	if id < 0:
		return null
	return get_item_by_id(id)

func get_description_by_name(_name : String):
	var item = get_item_by_name(_name)
	return item.description

func _init():
	for k in item_list:
		item_list[k].id = k
