# Generated from official items.dat (LEB128 records) - do not edit by hand
extends Object
class_name ItemPrices

const PRICES = {
	"Absorb Bulb": 200,
	"Acai Berry": 20,
	"Adamant Orb": 10000,
	"Aguav Berry": 20,
	"Air Balloon": 200,
	"Air Mail": 50,
	"Ampharosite": 999,
	"Amulet Coin": 100,
	"Antidote": 100,
	"Apicot Berry": 20,
	"Apricorn Box": 0,
	"Arbokite": 100,
	"Archillesite": 50000,
	"Armor Fossil": 1000,
	"Aromatic Herb": 100,
	"Aspear Berry": 20,
	"Assault Vest": 1000,
	"Atom Ball": 0,
	"Awakening": 250,
	"Azure Flute": 0,
	"BBFerry Ticket": 0,
	"Baariettite": 100,
	"Babiri Berry": 20,
	"Bacu Berry": 20,
	"Basement Key": 0,
	"Bead Mail": 50,
	"Belue Berry": 20,
	"Berry Juice": 100,
	"Berry Pots": 0,
	"Bicycle": 0,
	"Big Mushroom": 5000,
	"Big Pearl": 7500,
	"Big Root": 200,
	"Bike Wheel": 0,
	"Binding Band": 200,
	"Black Belt": 100,
	"Black Flute": 400,
	"Black Sludge": 200,
	"BlackGlasses": 100,
	"Blk Apricorn": 200,
	"Blu Apricorn": 200,
	"Blue Card": 0,
	"Blue Flute": 100,
	"Blue Orb": 0,
	"Blue Scarf": 100,
	"Blue Shard": 200,
	"Bluk Berry": 20,
	"Boxing Gloves": 0,
	"BrightPowder": 10,
	"Bug Gem": 200,
	"Bug Spray": 0,
	"Burn Heal": 250,
	"Burnt Notebook": 0,
	"Calcium": 9800,
	"Carbos": 9800,
	"Card Key": 0,
	"Carrot Wine": 1600,
	"Cell Battery": 200,
	"Charcoal": 9800,
	"Charti Berry": 20,
	"Cheri Berry": 20,
	"Cherish Ball": 200,
	"Chesto Berry": 20,
	"Chilan Berry": 20,
	"Choice Band": 15000,
	"Choice Scarf": 15000,
	"Choice Specs": 15000,
	"Chople Berry": 20,
	"Claw Fossil": 1000,
	"Cleanse Tag": 200,
	"Clear Bell": 0,
	"Climbing Pick": 0,
	"Coba Berry": 20,
	"Coconut Milk": 800,
	"Coin Case": 0,
	"Colbur Berry": 20,
	"Contest Pass": 0,
	"Cornn Berry": 20,
	"Coupon 1": 0,
	"Coupon 2": 0,
	"Coupon 3": 0,
	"Cupu Berry": 20,
	"Custap Berry": 20,
	"Daikatunite": 100,
	"Damp Mulch": 200,
	"Damp Rock": 200,
	"Dark Dramsamaite": 100,
	"Dark Gem": 200,
	"Dawn Stone": 2100,
	"DeepSeaScale": 200,
	"DeepSeaTooth": 200,
	"Destiny Knot": 200,
	"Dire Hit": 650,
	"Dive Ball": 1000,
	"Dome Fossil": 1000,
	"Dowsing MCHN": 0,
	"Draco Plate": 1000,
	"Dragon Fang": 100,
	"Dragon Gem": 200,
	"Dragon Scale": 2100,
	"Dramsamaite": 100,
	"Dread Plate": 1000,
	"Dream Mail": 50,
	"Drilgannite": 100,
	"Dubious Disc": 2100,
	"Durin Berry": 20,
	"Dusk Ball": 1000,
	"Dusk Stone": 2100,
	"Earth Plate": 1000,
	"Eject Button": 200,
	"Electirizer": 2100,
	"Electric Gem": 200,
	"Electruxolite": 50000,
	"Elixir": 3000,
	"Energy Root": 800,
	"EnergyPowder": 500,
	"Enigma Berry": 20,
	"Enigma Stone": 0,
	"Escape Rope": 550,
	"Ether": 1200,
	"Everstone": 200,
	"Eviolite": 200,
	"Exp. All": 0,
	"Exp. Share": 3000,
	"Expert Belt": 12000,
	"Explorer Kit": 0,
	"Fab Mail": 50,
	"Fairy Gem": 200,
	"Fashion Case": 0,
	"Fast Ball": 300,
	"Ferry Pass": 0,
	"Fighting Gem": 200,
	"Figy Berry": 20,
	"Fire Gem": 200,
	"Fire Stone": 2100,
	"Fist Plate": 1000,
	"Flame Orb": 8000,
	"Flame Plate": 1000,
	"Float Stone": 200,
	"Fluffy Tail": 1000,
	"Flying Gem": 200,
	"Focus Band": 10000,
	"Focus Sash": 14000,
	"Fresh Water": 200,
	"Friend Ball": 300,
	"Full Heal": 600,
	"Full Incense": 9600,
	"Full Restore": 3000,
	"GB Sounds": 0,
	"Galactic Key": 0,
	"Ganlon Berry": 20,
	"Gengarite": 1000,
	"Ghost Gem": 200,
	"Glitter Mail": 50,
	"Gold Fossil": 1000,
	"Good Rod": 0,
	"Gooey Mulch": 200,
	"Gracidea": 0,
	"Grass Gem": 200,
	"Great Ball": 600,
	"Green Scarf": 100,
	"Green Shard": 200,
	"Grepa Berry": 1000,
	"Grip Claw": 200,
	"Griseous Orb": 10000,
	"Grn Apricorn": 200,
	"Ground Gem": 200,
	"Growth Mulch": 200,
	"Guara Berry": 20,
	"Guard Spec.": 700,
	"Gyaradosite": 999,
	"HM01": 0,
	"HM02": 0,
	"HM03": 0,
	"HM04": 0,
	"HM05": 0,
	"HM06": 0,
	"HM07": 0,
	"HM08": 0,
	"HP Up": 9800,
	"Haban Berry": 20,
	"Hafli Berry": 20,
	"Hair Fossil": 1000,
	"Harbor Mail": 50,
	"Hard Stone": 100,
	"Heal Ball": 300,
	"Heal Powder": 450,
	"Heart Scale": 100,
	"Heat Rock": 200,
	"Heavy Ball": 300,
	"Helix Fossil": 1000,
	"Hondew Berry": 1000,
	"Honey": 100,
	"Hyper Potion": 1200,
	"Iapapa Berry": 20,
	"Ice Gem": 200,
	"Ice Heal": 250,
	"Ice Shard": 100,
	"Icicle Plate": 1000,
	"Icy Rock": 200,
	"Inflagetite": 100,
	"Insect Plate": 1000,
	"Iron": 9800,
	"Iron Ball": 200,
	"Iron Plate": 1000,
	"Jaboca Berry": 20,
	"Jade Orb": 0,
	"Journal": 0,
	"Jungle's Crown": 5500,
	"Kasib Berry": 20,
	"Kebia Berry": 20,
	"Kee Berry": 20,
	"Kellyn's Letter": 0,
	"Kelpsy Berry": 1000,
	"King's Rock": 100,
	"Kiricornite": 1000,
	"LAB KEY": 0,
	"Lagging Tail": 200,
	"Lansat Berry": 20,
	"Lava Cookie": 200,
	"Lax Incense": 9600,
	"Leaf Stone": 2100,
	"Leftovers": 200,
	"Lemonade": 350,
	"Leppa Berry": 20,
	"Level Ball": 300,
	"Liechi Berry": 20,
	"Life Orb": 20000,
	"Light Ball": 100,
	"Light Clay": 200,
	"Lock Capsule": 0,
	"Loot Sack": 0,
	"Lost Item": 0,
	"Love Ball": 300,
	"Luck Incense": 9600,
	"Lucky Egg": 200,
	"Lucky Punch": 10,
	"Lum Berry": 20,
	"Luminous Moss": 200,
	"Lunar Wing": 0,
	"Lure Ball": 300,
	"Lustrous Orb": 10000,
	"Luxury Ball": 1000,
	"Machine Part": 0,
	"Macho Brace": 3000,
	"Magma Stone": 0,
	"Magmarizer": 2100,
	"Magnet": 100,
	"Mago Berry": 20,
	"Magost Berry": 20,
	"Map Scrap 1": 0,
	"Map Scrap 2": 0,
	"Map Scrap 3": 0,
	"Map Scrap 4": 0,
	"Map Scrap 5": 0,
	"Map Scrap 6": 0,
	"Maranga Berry": 20,
	"Maria's Key": 0,
	"Master Ball": 0,
	"Max Elixir": 4500,
	"Max Ether": 2000,
	"Max Potion": 2500,
	"Max Repel": 700,
	"Max Revive": 4000,
	"Meadow Plate": 1000,
	"Mech Mail": 50,
	"Mega Bracelet": 0,
	"Member Card": 0,
	"Mental Herb": 100,
	"Metal Coat": 100,
	"Metal Powder": 10,
	"Metalynxite": 50000,
	"Metronome": 200,
	"Micle Berry": 20,
	"Mind Plate": 1000,
	"Miracle Seed": 100,
	"Moomoo Milk": 500,
	"Moon Ball": 300,
	"Moon Stone": 2100,
	"Moss Shard": 100,
	"Muscle Band": 200,
	"Mystery Egg": 0,
	"Mystic Water": 100,
	"Nanab Berry": 20,
	"Nest Ball": 1000,
	"Net Ball": 1000,
	"NeverMeltIce": 100,
	"Nomel Berry": 20,
	"Normal Gem": 200,
	"Nuclear Ball": 500,
	"Nugget": 10000,
	"Oak's Letter": 0,
	"Oblivicornite": 1000,
	"Occa Berry": 20,
	"Odd Incense": 9600,
	"Odd Keystone": 2100,
	"Old Amber": 1000,
	"Old Charm": 0,
	"Old Gateau": 200,
	"Old Rod": 0,
	"Oran Berry": 20,
	"Orange Mail": 50,
	"Oval Charm": 0,
	"Oval Stone": 2100,
	"PP Max": 9800,
	"PP Up": 9800,
	"PST": 0,
	"Pal Pad": 0,
	"Pamtre Berry": 20,
	"Parcel": 0,
	"Park Ball": 0,
	"Parlyz Heal": 200,
	"Pass": 0,
	"Passho Berry": 20,
	"Payapa Berry": 20,
	"Pearl": 1400,
	"Pecha Berry": 20,
	"Persim Berry": 20,
	"Petaya Berry": 20,
	"Photo Album": 0,
	"Pinap Berry": 20,
	"Pink Scarf": 100,
	"Pixie Plate": 1000,
	"Pnk Apricorn": 200,
	"Poffin Case": 0,
	"Point Card": 0,
	"Poison Barb": 100,
	"Poison Gem": 200,
	"Poké Ball": 200,
	"Poké Doll": 1000,
	"Poké Radar": 0,
	"Pomeg Berry": 1000,
	"Potion": 300,
	"Power Anklet": 3000,
	"Power Band": 3000,
	"Power Belt": 3000,
	"Power Bracer": 3000,
	"Power Cell": 0,
	"Power Glove": 0,
	"Power Herb": 100,
	"Power Lens": 3000,
	"Power Weight": 3000,
	"Premier Ball": 200,
	"Pretty Ribbon": 100,
	"Prison Bottle": 0,
	"Protector": 2100,
	"Protein": 9800,
	"Psychic Gem": 200,
	"Pure Incense": 9600,
	"Quadcopter": 0,
	"Qualot Berry": 1000,
	"Quick Ball": 1000,
	"Quick Claw": 100,
	"Quick Powder": 10,
	"Rabuta Berry": 20,
	"RageCandyBar": 300,
	"Rainbow Wing": 0,
	"Rare Bone": 10000,
	"Rare Candy": 4800,
	"Rawst Berry": 20,
	"Razor Claw": 2100,
	"Razor Fang": 2100,
	"Razz Berry": 20,
	"Reaper Cloth": 2100,
	"Red Apricorn": 200,
	"Red Card": 200,
	"Red Chain": 0,
	"Red Flute": 300,
	"Red Orb": 0,
	"Red Scale": 0,
	"Red Scarf": 100,
	"Red Shard": 200,
	"Repeat Ball": 1000,
	"Repel": 350,
	"Retro Mail": 50,
	"Revival Herb": 2800,
	"Revive": 1500,
	"Rich Mulch": 200,
	"Rindo Berry": 20,
	"Ring Target": 200,
	"Rock Gem": 200,
	"Rock Incense": 9600,
	"Rocky Helmet": 200,
	"Root Fossil": 1000,
	"Rose Incense": 9600,
	"Roseli Berry": 20,
	"Rowap Berry": 20,
	"Royal Jelly": 100,
	"Rule Book": 0,
	"Rusty Key": 0,
	"Sableyeite": 100,
	"Sachet": 100,
	"Sacred Ash": 200,
	"Safari Ball": 0,
	"Safety Goggles": 1000,
	"Salac Berry": 20,
	"Scope Lens": 12000,
	"Scuba Gear": 0,
	"Sea Incense": 9600,
	"Seal Bag": 0,
	"Seal Case": 0,
	"Secret Key": 0,
	"Secret Note": 0,
	"SecretPotion": 0,
	"Shadow Mail": 50,
	"Sharp Beak": 100,
	"Shed Shell": 100,
	"Shell Bell": 200,
	"Shiny Charm": 0,
	"Shiny Stone": 2100,
	"Shoal Salt": 20,
	"Shoal Shell": 20,
	"Shuca Berry": 20,
	"Silk Scarf": 100,
	"Silph Scope": 0,
	"Silver Wing": 0,
	"SilverPowder": 100,
	"Sitrus Berry": 20,
	"Skull Fossil": 1000,
	"Sky Plate": 1000,
	"SlowpokeTail": 0,
	"Smoke Ball": 200,
	"Smooth Rock": 200,
	"Snowball": 200,
	"Soda Pop": 300,
	"Soft Sand": 100,
	"Soot Sack": 0,
	"Soothe Bell": 100,
	"Soul Dew": 200,
	"Spell Tag": 100,
	"Spelon Berry": 20,
	"Splash Plate": 1000,
	"Spooky Plate": 1000,
	"Sport Ball": 0,
	"Sprayduck": 0,
	"Sprinklotad": 0,
	"Squirtbottle": 0,
	"Stable Mulch": 200,
	"Star Piece": 9800,
	"Stardust": 2000,
	"Starf Berry": 20,
	"Steel Gem": 200,
	"Stick": 200,
	"Sticker Case": 0,
	"Sticky Barb": 200,
	"Stone Plate": 1000,
	"Storage Key": 0,
	"Suite Key": 0,
	"Sun Stone": 2100,
	"Super Potion": 700,
	"Super Repel": 500,
	"Super Rod": 0,
	"Surfboard": 0,
	"Syrentideite": 100,
	"T.U.R Ticket": 250,
	"TM01": 30000,
	"TM02": 30000,
	"TM03": 30000,
	"TM04": 15000,
	"TM05": 10000,
	"TM06": 30000,
	"TM07": 20000,
	"TM08": 15000,
	"TM09": 20000,
	"TM10": 20000,
	"TM100": 0,
	"TM11": 20000,
	"TM12": 15000,
	"TM13": 30000,
	"TM14": 55000,
	"TM15": 75000,
	"TM16": 20000,
	"TM17": 20000,
	"TM18": 20000,
	"TM19": 30000,
	"TM20": 20000,
	"TM21": 10000,
	"TM22": 30000,
	"TM23": 30000,
	"TM24": 30000,
	"TM25": 55000,
	"TM26": 30000,
	"TM27": 10000,
	"TM28": 20000,
	"TM29": 30000,
	"TM30": 30000,
	"TM31": 30000,
	"TM32": 10000,
	"TM33": 20000,
	"TM34": 30000,
	"TM35": 30000,
	"TM36": 30000,
	"TM37": 20000,
	"TM38": 55000,
	"TM39": 20000,
	"TM40": 30000,
	"TM41": 15000,
	"TM42": 30000,
	"TM43": 20000,
	"TM44": 30000,
	"TM45": 30000,
	"TM46": 20000,
	"TM47": 30000,
	"TM48": 30000,
	"TM49": 15000,
	"TM50": 55000,
	"TM51": 20000,
	"TM52": 55000,
	"TM53": 30000,
	"TM54": 20000,
	"TM55": 30000,
	"TM56": 20000,
	"TM57": 30000,
	"TM58": 20000,
	"TM59": 30000,
	"TM60": 30000,
	"TM61": 20000,
	"TM62": 30000,
	"TM63": 20000,
	"TM64": 75000,
	"TM65": 30000,
	"TM66": 30000,
	"TM67": 10000,
	"TM68": 75000,
	"TM69": 15000,
	"TM70": 10000,
	"TM71": 30000,
	"TM72": 30000,
	"TM73": 20000,
	"TM74": 30000,
	"TM75": 15000,
	"TM76": 20000,
	"TM77": 15000,
	"TM78": 15000,
	"TM79": 30000,
	"TM80": 30000,
	"TM81": 30000,
	"TM82": 10000,
	"TM83": 20000,
	"TM84": 30000,
	"TM85": 30000,
	"TM86": 30000,
	"TM87": 15000,
	"TM88": 30000,
	"TM89": 30000,
	"TM90": 20000,
	"TM91": 30000,
	"TM92": 55000,
	"TM93": 30000,
	"TM94": 40000,
	"TM95": 50000,
	"TM96": 40000,
	"TM97": 0,
	"TM98": 0,
	"TM99": 0,
	"Tamato Berry": 1000,
	"Tanga Berry": 20,
	"Thick Club": 500,
	"Thunderstone": 2100,
	"Tidal Bell": 0,
	"Timer Ball": 1000,
	"TinyMushroom": 500,
	"Town Map": 0,
	"Toxic Orb": 8000,
	"Toxic Plate": 1000,
	"Tropic Mail": 50,
	"Tusk Fossil": 1000,
	"TwistedSpoon": 100,
	"Ultra Ball": 1200,
	"Unidentified Fallen Object": 100,
	"Unown Report": 0,
	"Up-Grade": 2100,
	"Uranium Core": 0,
	"Vs. Recorder": 0,
	"Vs. Seeker": 0,
	"Wacan Berry": 20,
	"Water Gem": 200,
	"Water Stone": 2100,
	"Watmel Berry": 20,
	"Wave Incense": 9600,
	"Wave Mail": 50,
	"Weakness Policy": 1000,
	"Wepear Berry": 20,
	"Whimsicottite": 100,
	"White Flute": 500,
	"White Herb": 100,
	"Wht Apricorn": 200,
	"Wide Lens": 12000,
	"Wiki Berry": 20,
	"Wise Glasses": 200,
	"Wood Mail": 50,
	"Works Key": 0,
	"X Accuracy": 950,
	"X Attack": 500,
	"X Defend": 550,
	"X Sp. Def": 350,
	"X Special": 350,
	"X Speed": 350,
	"Yache Berry": 20,
	"Yellow Flute": 200,
	"Yellow Scarf": 100,
	"Yellow Shard": 200,
	"Ylw Apricorn": 200,
	"Yoshitaka's Letter": 0,
	"Zap Plate": 1000,
	"Zinc": 9800,
	"Zoom Lens": 12000,
}

static func price_of(item_name: String) -> int:
	return PRICES.get(item_name, 0)

# Symbol map (event stock symbols like SUPERPOTION -> display names)
const SYMBOLS = {
	"ABSORBBULB": "Absorb Bulb",
	"ACAIBERRY": "Acai Berry",
	"ADAMANTORB": "Adamant Orb",
	"AGUAVBERRY": "Aguav Berry",
	"AIRBALLOON": "Air Balloon",
	"AIRMAIL": "Air Mail",
	"AMPHAROSITE": "Ampharosite",
	"AMULETCOIN": "Amulet Coin",
	"ANTIDOTE": "Antidote",
	"APICOTBERRY": "Apicot Berry",
	"APRICORNBOX": "Apricorn Box",
	"ARBOKITE": "Arbokite",
	"ARCHILLESITE": "Archillesite",
	"ARMORFOSSIL": "Armor Fossil",
	"AROMATICHERB": "Aromatic Herb",
	"ASPEARBERRY": "Aspear Berry",
	"ASSAULTVEST": "Assault Vest",
	"ATOMBALL": "Atom Ball",
	"AWAKENING": "Awakening",
	"AZUREFLUTE": "Azure Flute",
	"BBFERRYTICKET": "BBFerry Ticket",
	"BAARIETTITE": "Baariettite",
	"BABIRIBERRY": "Babiri Berry",
	"BACUBERRY": "Bacu Berry",
	"BASEMENTKEY": "Basement Key",
	"BEADMAIL": "Bead Mail",
	"BELUEBERRY": "Belue Berry",
	"BERRYJUICE": "Berry Juice",
	"BERRYPOTS": "Berry Pots",
	"BICYCLE": "Bicycle",
	"BIGMUSHROOM": "Big Mushroom",
	"BIGPEARL": "Big Pearl",
	"BIGROOT": "Big Root",
	"BIKEWHEEL": "Bike Wheel",
	"BINDINGBAND": "Binding Band",
	"BLACKBELT": "Black Belt",
	"BLACKFLUTE": "Black Flute",
	"BLACKSLUDGE": "Black Sludge",
	"BLACKGLASSES": "BlackGlasses",
	"BLKAPRICORN": "Blk Apricorn",
	"BLUAPRICORN": "Blu Apricorn",
	"BLUECARD": "Blue Card",
	"BLUEFLUTE": "Blue Flute",
	"BLUEORB": "Blue Orb",
	"BLUESCARF": "Blue Scarf",
	"BLUESHARD": "Blue Shard",
	"BLUKBERRY": "Bluk Berry",
	"BOXINGGLOVES": "Boxing Gloves",
	"BRIGHTPOWDER": "BrightPowder",
	"BUGGEM": "Bug Gem",
	"BUGSPRAY": "Bug Spray",
	"BURNHEAL": "Burn Heal",
	"BURNTNOTEBOOK": "Burnt Notebook",
	"CALCIUM": "Calcium",
	"CARBOS": "Carbos",
	"CARDKEY": "Card Key",
	"CARROTWINE": "Carrot Wine",
	"CELLBATTERY": "Cell Battery",
	"CHARCOAL": "Charcoal",
	"CHARTIBERRY": "Charti Berry",
	"CHERIBERRY": "Cheri Berry",
	"CHERISHBALL": "Cherish Ball",
	"CHESTOBERRY": "Chesto Berry",
	"CHILANBERRY": "Chilan Berry",
	"CHOICEBAND": "Choice Band",
	"CHOICESCARF": "Choice Scarf",
	"CHOICESPECS": "Choice Specs",
	"CHOPLEBERRY": "Chople Berry",
	"CLAWFOSSIL": "Claw Fossil",
	"CLEANSETAG": "Cleanse Tag",
	"CLEARBELL": "Clear Bell",
	"CLIMBINGPICK": "Climbing Pick",
	"COBABERRY": "Coba Berry",
	"COCONUTMILK": "Coconut Milk",
	"COINCASE": "Coin Case",
	"COLBURBERRY": "Colbur Berry",
	"CONTESTPASS": "Contest Pass",
	"CORNNBERRY": "Cornn Berry",
	"COUPON1": "Coupon 1",
	"COUPON2": "Coupon 2",
	"COUPON3": "Coupon 3",
	"CUPUBERRY": "Cupu Berry",
	"CUSTAPBERRY": "Custap Berry",
	"DAIKATUNITE": "Daikatunite",
	"DAMPMULCH": "Damp Mulch",
	"DAMPROCK": "Damp Rock",
	"DARKDRAMSAMAITE": "Dark Dramsamaite",
	"DARKGEM": "Dark Gem",
	"DAWNSTONE": "Dawn Stone",
	"DEEPSEASCALE": "DeepSeaScale",
	"DEEPSEATOOTH": "DeepSeaTooth",
	"DESTINYKNOT": "Destiny Knot",
	"DIREHIT": "Dire Hit",
	"DIVEBALL": "Dive Ball",
	"DOMEFOSSIL": "Dome Fossil",
	"DOWSINGMCHN": "Dowsing MCHN",
	"DRACOPLATE": "Draco Plate",
	"DRAGONFANG": "Dragon Fang",
	"DRAGONGEM": "Dragon Gem",
	"DRAGONSCALE": "Dragon Scale",
	"DRAMSAMAITE": "Dramsamaite",
	"DREADPLATE": "Dread Plate",
	"DREAMMAIL": "Dream Mail",
	"DRILGANNITE": "Drilgannite",
	"DUBIOUSDISC": "Dubious Disc",
	"DURINBERRY": "Durin Berry",
	"DUSKBALL": "Dusk Ball",
	"DUSKSTONE": "Dusk Stone",
	"EARTHPLATE": "Earth Plate",
	"EJECTBUTTON": "Eject Button",
	"ELECTIRIZER": "Electirizer",
	"ELECTRICGEM": "Electric Gem",
	"ELECTRUXOLITE": "Electruxolite",
	"ELIXIR": "Elixir",
	"ENERGYROOT": "Energy Root",
	"ENERGYPOWDER": "EnergyPowder",
	"ENIGMABERRY": "Enigma Berry",
	"ENIGMASTONE": "Enigma Stone",
	"ESCAPEROPE": "Escape Rope",
	"ETHER": "Ether",
	"EVERSTONE": "Everstone",
	"EVIOLITE": "Eviolite",
	"EXPALL": "Exp. All",
	"EXPSHARE": "Exp. Share",
	"EXPERTBELT": "Expert Belt",
	"EXPLORERKIT": "Explorer Kit",
	"FABMAIL": "Fab Mail",
	"FAIRYGEM": "Fairy Gem",
	"FASHIONCASE": "Fashion Case",
	"FASTBALL": "Fast Ball",
	"FERRYPASS": "Ferry Pass",
	"FIGHTINGGEM": "Fighting Gem",
	"FIGYBERRY": "Figy Berry",
	"FIREGEM": "Fire Gem",
	"FIRESTONE": "Fire Stone",
	"FISTPLATE": "Fist Plate",
	"FLAMEORB": "Flame Orb",
	"FLAMEPLATE": "Flame Plate",
	"FLOATSTONE": "Float Stone",
	"FLUFFYTAIL": "Fluffy Tail",
	"FLYINGGEM": "Flying Gem",
	"FOCUSBAND": "Focus Band",
	"FOCUSSASH": "Focus Sash",
	"FRESHWATER": "Fresh Water",
	"FRIENDBALL": "Friend Ball",
	"FULLHEAL": "Full Heal",
	"FULLINCENSE": "Full Incense",
	"FULLRESTORE": "Full Restore",
	"GBSOUNDS": "GB Sounds",
	"GALACTICKEY": "Galactic Key",
	"GANLONBERRY": "Ganlon Berry",
	"GENGARITE": "Gengarite",
	"GHOSTGEM": "Ghost Gem",
	"GLITTERMAIL": "Glitter Mail",
	"GOLDFOSSIL": "Gold Fossil",
	"GOODROD": "Good Rod",
	"GOOEYMULCH": "Gooey Mulch",
	"GRACIDEA": "Gracidea",
	"GRASSGEM": "Grass Gem",
	"GREATBALL": "Great Ball",
	"GREENSCARF": "Green Scarf",
	"GREENSHARD": "Green Shard",
	"GREPABERRY": "Grepa Berry",
	"GRIPCLAW": "Grip Claw",
	"GRISEOUSORB": "Griseous Orb",
	"GRNAPRICORN": "Grn Apricorn",
	"GROUNDGEM": "Ground Gem",
	"GROWTHMULCH": "Growth Mulch",
	"GUARABERRY": "Guara Berry",
	"GUARDSPEC": "Guard Spec.",
	"GYARADOSITE": "Gyaradosite",
	"HM01": "HM01",
	"HM02": "HM02",
	"HM03": "HM03",
	"HM04": "HM04",
	"HM05": "HM05",
	"HM06": "HM06",
	"HM07": "HM07",
	"HM08": "HM08",
	"HPUP": "HP Up",
	"HABANBERRY": "Haban Berry",
	"HAFLIBERRY": "Hafli Berry",
	"HAIRFOSSIL": "Hair Fossil",
	"HARBORMAIL": "Harbor Mail",
	"HARDSTONE": "Hard Stone",
	"HEALBALL": "Heal Ball",
	"HEALPOWDER": "Heal Powder",
	"HEARTSCALE": "Heart Scale",
	"HEATROCK": "Heat Rock",
	"HEAVYBALL": "Heavy Ball",
	"HELIXFOSSIL": "Helix Fossil",
	"HONDEWBERRY": "Hondew Berry",
	"HONEY": "Honey",
	"HYPERPOTION": "Hyper Potion",
	"IAPAPABERRY": "Iapapa Berry",
	"ICEGEM": "Ice Gem",
	"ICEHEAL": "Ice Heal",
	"ICESHARD": "Ice Shard",
	"ICICLEPLATE": "Icicle Plate",
	"ICYROCK": "Icy Rock",
	"INFLAGETITE": "Inflagetite",
	"INSECTPLATE": "Insect Plate",
	"IRON": "Iron",
	"IRONBALL": "Iron Ball",
	"IRONPLATE": "Iron Plate",
	"JABOCABERRY": "Jaboca Berry",
	"JADEORB": "Jade Orb",
	"JOURNAL": "Journal",
	"JUNGLESCROWN": "Jungle's Crown",
	"KASIBBERRY": "Kasib Berry",
	"KEBIABERRY": "Kebia Berry",
	"KEEBERRY": "Kee Berry",
	"KELLYNSLETTER": "Kellyn's Letter",
	"KELPSYBERRY": "Kelpsy Berry",
	"KINGSROCK": "King's Rock",
	"KIRICORNITE": "Kiricornite",
	"LABKEY": "LAB KEY",
	"LAGGINGTAIL": "Lagging Tail",
	"LANSATBERRY": "Lansat Berry",
	"LAVACOOKIE": "Lava Cookie",
	"LAXINCENSE": "Lax Incense",
	"LEAFSTONE": "Leaf Stone",
	"LEFTOVERS": "Leftovers",
	"LEMONADE": "Lemonade",
	"LEPPABERRY": "Leppa Berry",
	"LEVELBALL": "Level Ball",
	"LIECHIBERRY": "Liechi Berry",
	"LIFEORB": "Life Orb",
	"LIGHTBALL": "Light Ball",
	"LIGHTCLAY": "Light Clay",
	"LOCKCAPSULE": "Lock Capsule",
	"LOOTSACK": "Loot Sack",
	"LOSTITEM": "Lost Item",
	"LOVEBALL": "Love Ball",
	"LUCKINCENSE": "Luck Incense",
	"LUCKYEGG": "Lucky Egg",
	"LUCKYPUNCH": "Lucky Punch",
	"LUMBERRY": "Lum Berry",
	"LUMINOUSMOSS": "Luminous Moss",
	"LUNARWING": "Lunar Wing",
	"LUREBALL": "Lure Ball",
	"LUSTROUSORB": "Lustrous Orb",
	"LUXURYBALL": "Luxury Ball",
	"MACHINEPART": "Machine Part",
	"MACHOBRACE": "Macho Brace",
	"MAGMASTONE": "Magma Stone",
	"MAGMARIZER": "Magmarizer",
	"MAGNET": "Magnet",
	"MAGOBERRY": "Mago Berry",
	"MAGOSTBERRY": "Magost Berry",
	"MAPSCRAP1": "Map Scrap 1",
	"MAPSCRAP2": "Map Scrap 2",
	"MAPSCRAP3": "Map Scrap 3",
	"MAPSCRAP4": "Map Scrap 4",
	"MAPSCRAP5": "Map Scrap 5",
	"MAPSCRAP6": "Map Scrap 6",
	"MARANGABERRY": "Maranga Berry",
	"MARIASKEY": "Maria's Key",
	"MASTERBALL": "Master Ball",
	"MAXELIXIR": "Max Elixir",
	"MAXETHER": "Max Ether",
	"MAXPOTION": "Max Potion",
	"MAXREPEL": "Max Repel",
	"MAXREVIVE": "Max Revive",
	"MEADOWPLATE": "Meadow Plate",
	"MECHMAIL": "Mech Mail",
	"MEGABRACELET": "Mega Bracelet",
	"MEMBERCARD": "Member Card",
	"MENTALHERB": "Mental Herb",
	"METALCOAT": "Metal Coat",
	"METALPOWDER": "Metal Powder",
	"METALYNXITE": "Metalynxite",
	"METRONOME": "Metronome",
	"MICLEBERRY": "Micle Berry",
	"MINDPLATE": "Mind Plate",
	"MIRACLESEED": "Miracle Seed",
	"MOOMOOMILK": "Moomoo Milk",
	"MOONBALL": "Moon Ball",
	"MOONSTONE": "Moon Stone",
	"MOSSSHARD": "Moss Shard",
	"MUSCLEBAND": "Muscle Band",
	"MYSTERYEGG": "Mystery Egg",
	"MYSTICWATER": "Mystic Water",
	"NANABBERRY": "Nanab Berry",
	"NESTBALL": "Nest Ball",
	"NETBALL": "Net Ball",
	"NEVERMELTICE": "NeverMeltIce",
	"NOMELBERRY": "Nomel Berry",
	"NORMALGEM": "Normal Gem",
	"NUCLEARBALL": "Nuclear Ball",
	"NUGGET": "Nugget",
	"OAKSLETTER": "Oak's Letter",
	"OBLIVICORNITE": "Oblivicornite",
	"OCCABERRY": "Occa Berry",
	"ODDINCENSE": "Odd Incense",
	"ODDKEYSTONE": "Odd Keystone",
	"OLDAMBER": "Old Amber",
	"OLDCHARM": "Old Charm",
	"OLDGATEAU": "Old Gateau",
	"OLDROD": "Old Rod",
	"ORANBERRY": "Oran Berry",
	"ORANGEMAIL": "Orange Mail",
	"OVALCHARM": "Oval Charm",
	"OVALSTONE": "Oval Stone",
	"PPMAX": "PP Max",
	"PPUP": "PP Up",
	"PST": "PST",
	"PALPAD": "Pal Pad",
	"PAMTREBERRY": "Pamtre Berry",
	"PARCEL": "Parcel",
	"PARKBALL": "Park Ball",
	"PARLYZHEAL": "Parlyz Heal",
	"PASS": "Pass",
	"PASSHOBERRY": "Passho Berry",
	"PAYAPABERRY": "Payapa Berry",
	"PEARL": "Pearl",
	"PECHABERRY": "Pecha Berry",
	"PERSIMBERRY": "Persim Berry",
	"PETAYABERRY": "Petaya Berry",
	"PHOTOALBUM": "Photo Album",
	"PINAPBERRY": "Pinap Berry",
	"PINKSCARF": "Pink Scarf",
	"PIXIEPLATE": "Pixie Plate",
	"PNKAPRICORN": "Pnk Apricorn",
	"POFFINCASE": "Poffin Case",
	"POINTCARD": "Point Card",
	"POISONBARB": "Poison Barb",
	"POISONGEM": "Poison Gem",
	"POKEBALL": "Poké Ball",
	"POKEDOLL": "Poké Doll",
	"POKERADAR": "Poké Radar",
	"POMEGBERRY": "Pomeg Berry",
	"POTION": "Potion",
	"POWERANKLET": "Power Anklet",
	"POWERBAND": "Power Band",
	"POWERBELT": "Power Belt",
	"POWERBRACER": "Power Bracer",
	"POWERCELL": "Power Cell",
	"POWERGLOVE": "Power Glove",
	"POWERHERB": "Power Herb",
	"POWERLENS": "Power Lens",
	"POWERWEIGHT": "Power Weight",
	"PREMIERBALL": "Premier Ball",
	"PRETTYRIBBON": "Pretty Ribbon",
	"PRISONBOTTLE": "Prison Bottle",
	"PROTECTOR": "Protector",
	"PROTEIN": "Protein",
	"PSYCHICGEM": "Psychic Gem",
	"PUREINCENSE": "Pure Incense",
	"QUADCOPTER": "Quadcopter",
	"QUALOTBERRY": "Qualot Berry",
	"QUICKBALL": "Quick Ball",
	"QUICKCLAW": "Quick Claw",
	"QUICKPOWDER": "Quick Powder",
	"RABUTABERRY": "Rabuta Berry",
	"RAGECANDYBAR": "RageCandyBar",
	"RAINBOWWING": "Rainbow Wing",
	"RAREBONE": "Rare Bone",
	"RARECANDY": "Rare Candy",
	"RAWSTBERRY": "Rawst Berry",
	"RAZORCLAW": "Razor Claw",
	"RAZORFANG": "Razor Fang",
	"RAZZBERRY": "Razz Berry",
	"REAPERCLOTH": "Reaper Cloth",
	"REDAPRICORN": "Red Apricorn",
	"REDCARD": "Red Card",
	"REDCHAIN": "Red Chain",
	"REDFLUTE": "Red Flute",
	"REDORB": "Red Orb",
	"REDSCALE": "Red Scale",
	"REDSCARF": "Red Scarf",
	"REDSHARD": "Red Shard",
	"REPEATBALL": "Repeat Ball",
	"REPEL": "Repel",
	"RETROMAIL": "Retro Mail",
	"REVIVALHERB": "Revival Herb",
	"REVIVE": "Revive",
	"RICHMULCH": "Rich Mulch",
	"RINDOBERRY": "Rindo Berry",
	"RINGTARGET": "Ring Target",
	"ROCKGEM": "Rock Gem",
	"ROCKINCENSE": "Rock Incense",
	"ROCKYHELMET": "Rocky Helmet",
	"ROOTFOSSIL": "Root Fossil",
	"ROSEINCENSE": "Rose Incense",
	"ROSELIBERRY": "Roseli Berry",
	"ROWAPBERRY": "Rowap Berry",
	"ROYALJELLY": "Royal Jelly",
	"RULEBOOK": "Rule Book",
	"RUSTYKEY": "Rusty Key",
	"SABLEYEITE": "Sableyeite",
	"SACHET": "Sachet",
	"SACREDASH": "Sacred Ash",
	"SAFARIBALL": "Safari Ball",
	"SAFETYGOGGLES": "Safety Goggles",
	"SALACBERRY": "Salac Berry",
	"SCOPELENS": "Scope Lens",
	"SCUBAGEAR": "Scuba Gear",
	"SEAINCENSE": "Sea Incense",
	"SEALBAG": "Seal Bag",
	"SEALCASE": "Seal Case",
	"SECRETKEY": "Secret Key",
	"SECRETNOTE": "Secret Note",
	"SECRETPOTION": "SecretPotion",
	"SHADOWMAIL": "Shadow Mail",
	"SHARPBEAK": "Sharp Beak",
	"SHEDSHELL": "Shed Shell",
	"SHELLBELL": "Shell Bell",
	"SHINYCHARM": "Shiny Charm",
	"SHINYSTONE": "Shiny Stone",
	"SHOALSALT": "Shoal Salt",
	"SHOALSHELL": "Shoal Shell",
	"SHUCABERRY": "Shuca Berry",
	"SILKSCARF": "Silk Scarf",
	"SILPHSCOPE": "Silph Scope",
	"SILVERWING": "Silver Wing",
	"SILVERPOWDER": "SilverPowder",
	"SITRUSBERRY": "Sitrus Berry",
	"SKULLFOSSIL": "Skull Fossil",
	"SKYPLATE": "Sky Plate",
	"SLOWPOKETAIL": "SlowpokeTail",
	"SMOKEBALL": "Smoke Ball",
	"SMOOTHROCK": "Smooth Rock",
	"SNOWBALL": "Snowball",
	"SODAPOP": "Soda Pop",
	"SOFTSAND": "Soft Sand",
	"SOOTSACK": "Soot Sack",
	"SOOTHEBELL": "Soothe Bell",
	"SOULDEW": "Soul Dew",
	"SPELLTAG": "Spell Tag",
	"SPELONBERRY": "Spelon Berry",
	"SPLASHPLATE": "Splash Plate",
	"SPOOKYPLATE": "Spooky Plate",
	"SPORTBALL": "Sport Ball",
	"SPRAYDUCK": "Sprayduck",
	"SPRINKLOTAD": "Sprinklotad",
	"SQUIRTBOTTLE": "Squirtbottle",
	"STABLEMULCH": "Stable Mulch",
	"STARPIECE": "Star Piece",
	"STARDUST": "Stardust",
	"STARFBERRY": "Starf Berry",
	"STEELGEM": "Steel Gem",
	"STICK": "Stick",
	"STICKERCASE": "Sticker Case",
	"STICKYBARB": "Sticky Barb",
	"STONEPLATE": "Stone Plate",
	"STORAGEKEY": "Storage Key",
	"SUITEKEY": "Suite Key",
	"SUNSTONE": "Sun Stone",
	"SUPERPOTION": "Super Potion",
	"SUPERREPEL": "Super Repel",
	"SUPERROD": "Super Rod",
	"SURFBOARD": "Surfboard",
	"SYRENTIDEITE": "Syrentideite",
	"TURTICKET": "T.U.R Ticket",
	"TM01": "TM01",
	"TM02": "TM02",
	"TM03": "TM03",
	"TM04": "TM04",
	"TM05": "TM05",
	"TM06": "TM06",
	"TM07": "TM07",
	"TM08": "TM08",
	"TM09": "TM09",
	"TM10": "TM10",
	"TM100": "TM100",
	"TM11": "TM11",
	"TM12": "TM12",
	"TM13": "TM13",
	"TM14": "TM14",
	"TM15": "TM15",
	"TM16": "TM16",
	"TM17": "TM17",
	"TM18": "TM18",
	"TM19": "TM19",
	"TM20": "TM20",
	"TM21": "TM21",
	"TM22": "TM22",
	"TM23": "TM23",
	"TM24": "TM24",
	"TM25": "TM25",
	"TM26": "TM26",
	"TM27": "TM27",
	"TM28": "TM28",
	"TM29": "TM29",
	"TM30": "TM30",
	"TM31": "TM31",
	"TM32": "TM32",
	"TM33": "TM33",
	"TM34": "TM34",
	"TM35": "TM35",
	"TM36": "TM36",
	"TM37": "TM37",
	"TM38": "TM38",
	"TM39": "TM39",
	"TM40": "TM40",
	"TM41": "TM41",
	"TM42": "TM42",
	"TM43": "TM43",
	"TM44": "TM44",
	"TM45": "TM45",
	"TM46": "TM46",
	"TM47": "TM47",
	"TM48": "TM48",
	"TM49": "TM49",
	"TM50": "TM50",
	"TM51": "TM51",
	"TM52": "TM52",
	"TM53": "TM53",
	"TM54": "TM54",
	"TM55": "TM55",
	"TM56": "TM56",
	"TM57": "TM57",
	"TM58": "TM58",
	"TM59": "TM59",
	"TM60": "TM60",
	"TM61": "TM61",
	"TM62": "TM62",
	"TM63": "TM63",
	"TM64": "TM64",
	"TM65": "TM65",
	"TM66": "TM66",
	"TM67": "TM67",
	"TM68": "TM68",
	"TM69": "TM69",
	"TM70": "TM70",
	"TM71": "TM71",
	"TM72": "TM72",
	"TM73": "TM73",
	"TM74": "TM74",
	"TM75": "TM75",
	"TM76": "TM76",
	"TM77": "TM77",
	"TM78": "TM78",
	"TM79": "TM79",
	"TM80": "TM80",
	"TM81": "TM81",
	"TM82": "TM82",
	"TM83": "TM83",
	"TM84": "TM84",
	"TM85": "TM85",
	"TM86": "TM86",
	"TM87": "TM87",
	"TM88": "TM88",
	"TM89": "TM89",
	"TM90": "TM90",
	"TM91": "TM91",
	"TM92": "TM92",
	"TM93": "TM93",
	"TM94": "TM94",
	"TM95": "TM95",
	"TM96": "TM96",
	"TM97": "TM97",
	"TM98": "TM98",
	"TM99": "TM99",
	"TAMATOBERRY": "Tamato Berry",
	"TANGABERRY": "Tanga Berry",
	"THICKCLUB": "Thick Club",
	"THUNDERSTONE": "Thunderstone",
	"TIDALBELL": "Tidal Bell",
	"TIMERBALL": "Timer Ball",
	"TINYMUSHROOM": "TinyMushroom",
	"TOWNMAP": "Town Map",
	"TOXICORB": "Toxic Orb",
	"TOXICPLATE": "Toxic Plate",
	"TROPICMAIL": "Tropic Mail",
	"TUSKFOSSIL": "Tusk Fossil",
	"TWISTEDSPOON": "TwistedSpoon",
	"ULTRABALL": "Ultra Ball",
	"UNIDENTIFIEDFALLENOBJECT": "Unidentified Fallen Object",
	"UNOWNREPORT": "Unown Report",
	"UPGRADE": "Up-Grade",
	"URANIUMCORE": "Uranium Core",
	"VSRECORDER": "Vs. Recorder",
	"VSSEEKER": "Vs. Seeker",
	"WACANBERRY": "Wacan Berry",
	"WATERGEM": "Water Gem",
	"WATERSTONE": "Water Stone",
	"WATMELBERRY": "Watmel Berry",
	"WAVEINCENSE": "Wave Incense",
	"WAVEMAIL": "Wave Mail",
	"WEAKNESSPOLICY": "Weakness Policy",
	"WEPEARBERRY": "Wepear Berry",
	"WHIMSICOTTITE": "Whimsicottite",
	"WHITEFLUTE": "White Flute",
	"WHITEHERB": "White Herb",
	"WHTAPRICORN": "Wht Apricorn",
	"WIDELENS": "Wide Lens",
	"WIKIBERRY": "Wiki Berry",
	"WISEGLASSES": "Wise Glasses",
	"WOODMAIL": "Wood Mail",
	"WORKSKEY": "Works Key",
	"XACCURACY": "X Accuracy",
	"XATTACK": "X Attack",
	"XDEFEND": "X Defend",
	"XSPDEF": "X Sp. Def",
	"XSPECIAL": "X Special",
	"XSPEED": "X Speed",
	"YACHEBERRY": "Yache Berry",
	"YELLOWFLUTE": "Yellow Flute",
	"YELLOWSCARF": "Yellow Scarf",
	"YELLOWSHARD": "Yellow Shard",
	"YLWAPRICORN": "Ylw Apricorn",
	"YOSHITAKASLETTER": "Yoshitaka's Letter",
	"ZAPPLATE": "Zap Plate",
	"ZINC": "Zinc",
	"ZOOMLENS": "Zoom Lens",
}

static func name_from_symbol(sym: String) -> String:
	return SYMBOLS.get(sym.to_upper(), "")
